### PR TITLE
Gruwice-Gamble

### PR DESCRIPTION
**Pull request by Arkangel-Vigilamus**
Mission Pull Request Template

This Pull Request will:

Add the mission <mission name!> made by <author name!> to the repository.

**Mission Creation Checklist:**
- [X] Mission File
- [X] Ingame Play Area Markers
- [X] Ingame Briefings to all players
- [NA] Side-based briefings
- [ ] Objective Entities
- [X] Mission .conf file

**Faction(s):**
BLUFOR - Attacking
- [ ] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [X] RHS_US_USMC
- [ ] BUNDESWEHR (US)

OPFOR - Defending
- [ ] USSR
- [ ] US
- [X] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

INDFOR - NA
- [ ] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

**Objectives/Win Conditions:**

Basic S&D

**Terrain:**

Zimnitrita

**Short mission description:**

USMC motorized platoon attempts to destroy two MSV positions within the town of Gruwice

**Slotting Ratio:**

BLU 3:2 OPF

**Time limit:**

45min

**Mission Briefing Screenshot:**

Will add later

**Design concept/thoughts:**

I'm not married to the bombsite locations, would be willing to move them closer or farther apart.

**Other Notes:**

2x M113A3 for BLU

### CODE REVIEW

**Comment by Arkangel-Vigilamus** [comment]
ArmaReforgerWorkbenchSteamDiag_w3XCypbL83

**Comment by RandAlThor1** [comment]
QA Feedback


- I like A site, perhaps moving B site towards the town office could help split up defenders enough for the bridges to be less hell.

- I see the commit for objectives but I don't see them in the lobby when testing.

- 6 squads in 1 platoon is too many, add a company and second platoon element even if they get locked due to numbers it helps with structure.

- I won't require individual side briefs for S&D but general situatuon/briefs are required to help provide a bit of context. (example below)


image

**Comment by Arkangel-Vigilamus** [comment]
ArmaReforgerWorkbenchSteamDiag_6oBzekC0vC

**Comment by Arkangel-Vigilamus** [comment]
ArmaReforgerWorkbenchSteamDiag_w1M2S9cP0S

**Comment by RandAlThor1** [comment]
QA Feedback

- US 2nd platoon comes first ( see image )

everything else looks good to me!

image

**Comment by tanaaKa** [comment]
> ArmaReforgerWorkbenchSteamDiag_w1M2S9cP0S

Not up to me, but having separate objectives per bombsite is nice.

Then title them `OBJ: Bomb Site A` etc... and it looks good in briefing.

**Comment by tanaaKa** [comment]
Also don't forget to put the objective entity order the highest number

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
