### PR TITLE
Mission/sal forest fuckery

### PR DESCRIPTION
**Pull request by Salamiboio**
Mission Pull Request Template

This Pull Request will:

Add the mission <mission name!> made by <author name!> to the repository.

**Mission Creation Checklist:**
- [X] Mission File
- [X] Ingame Play Area Markers
- [X] Ingame Briefings to all players
- [X] Side-based briefings
- [X] Objective Entities
- [X] Mission .conf file

**Faction(s):**
BLUFOR - Attacking

- [ ] USSR
- [X] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

OPFOR - Defending

- [X] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

**Objectives/Win Conditions:**

BLUFOR - Prevent the Soviets from extracting all their supplies in the town of Tyrone.
OPFOR - Extract all supplies in the town of Tyrone and successfully retreat from Tyrone.

**Terrain:**

Eden

**Short mission description:**

A dismounted BLUFOR platoon must breakthrough and prevent the Soviets from extracting supplies in Tyrone.

**Slotting Ratio:**

BLU 3:2 OPF

**Time limit:**

60 minutes

**Mission Briefing Screenshot:**
image

**Design concept/thoughts:**

A mission not just based on time but extracting supplies giving OPFOR a reason to push out and meet BLUFOR.

**Other Notes:**

- 9 Gazs for OPFOR as I don't want Urals farrying supplies.
- MI-8 for supply transport.
One supply run takes ~5 minutes with my mediocre flying so I set it to 8 supply runs to fully extract all supplies. making it take ~40 minutes to extract all supplies. This should give BLUFOR enough time to move into the area at least and make it a close fight.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
QA Feedback

- I have serious concerns about how long it will actually take to move all of the supplies.
- for OPFOR objective its unclear as to what purpose the "extract" portion really serves, how many need to extract? what does this actually add to the mission?
- moving boxes back and fourth for ~40 minutes sounds like an awful experience and really doesn't  interact with the mission at large other than acting as a glorified timer.
- none of the objective is scripted so we will have no indicator as to when all of the supplies have been moved.
- for BLUFOR objective, as of their brief just getting people in to town is enough to win, but their objective states supplies and helicopters are part of it, what is their actual win condition.
- move blufor LOA to behind the town, there is 100% a scenario where they can see opfor before safe-start ends.

Overall I fail to see what this change in objective actually brings to the mission that the old one didn't. having a asset move stuff in the background is a huge variable that blufor can't control because of how long it can take them to get there, what happens if the pilot crashes.

**Comment by tanaaKa** [comment]
> for OPFOR objective its unclear as to what purpose the "extract" portion really serves, how many need to extract? what does this actually add to the mission?
> moving boxes back and fourth for ~40 minutes sounds like an awful experience and really doesn't interact with the mission at large other than acting as a glorified timer.

I told him to give defenders something to actually do. "Defend X for X minutes" is not conducive to good game play. If attackers have an obj, defenders should as well.

**Comment by RandAlThor1** [comment]
> > for OPFOR objective its unclear as to what purpose the "extract" portion really serves, how many need to extract? what does this actually add to the mission?
> > moving boxes back and fourth for ~40 minutes sounds like an awful experience and really doesn't interact with the mission at large other than acting as a glorified timer.
> 
> I told him to give defenders something to actually do. "Defend X for X minutes" is not conducive to good game play. If attackers have an obj, defenders should as well.

We've done many mission where defenders primary goal was to defend an area, I figured opfor having vehicles allowed them to take on a more dynamic defense vs the dismounted blufor.

I'm also not against giving them an objective, I'm just worried that this is too variable and could either be completed very quickly, result in a crashed helo kind of ruining their whole goal on one persons fuck up, or take longer than expect and not be feasible.

**Comment by Salamiboio** [comment]
> > > for OPFOR objective its unclear as to what purpose the "extract" portion really serves, how many need to extract? what does this actually add to the mission?
> > > moving boxes back and fourth for ~40 minutes sounds like an awful experience and really doesn't interact with the mission at large other than acting as a glorified timer.
> > 
> > 
> > I told him to give defenders something to actually do. "Defend X for X minutes" is not conducive to good game play. If attackers have an obj, defenders should as well.
> 
> We've done many mission where defenders primary goal was to defend an area, I figured opfor having vehicles allowed them to take on a more dynamic defense vs the dismounted blufor.
> 
> I'm also not against giving them an objective, I'm just worried that this is too variable and could either be completed very quickly, result in a crashed helo kind of ruining their whole goal on one persons fuck up, or take longer than expect and not be feasible.

I timed runs with the helicopter myself, not knowing how to fly in reforger and it took me 4 minutes 20 seconds so estimating 5 is being extremely generous. It should get done earlier than that. However I do see your concern that if a helicopter pilot crashes it will ruin it. I could give OPFOR a UAZ that can carry supplies as well to the airbase in case this doomsday scenario happens. This UAZ will have a boost to the regular supply capacity so it takes 200 supplies.

**Comment by Salamiboio** [comment]
Fixed the briefings.
Added scripts to alert players to both when the Soviets have extracted all supplies and when Soviet forces have either extracted or don't have enough forces left.
Do note for testing that if there are not at least 8 Opfor the mission will end with the Soviets getting destroyed.

**Comment by RandAlThor1** [comment]
QA Feedback

- Don't end the mission until all of one side is dead, I understand the OBJ is 8 which is fair, but we try not to have missions end in the middle of firefights. Have the script send a message when OPFOR has less then 8, but end the mission when none are left. a admin can end the mission otherwise.
- move BLUFOR LOA to behind the town, there is 100% a scenario where they can see OPFORbefore safe-start ends.

**Comment by Salamiboio** [comment]
Edited the script so it only ends when 0 Soviets are remaining, added a notification that tells the Soviets when retreat is no longer possible due to manpower. 

Pushbacked BLUFOR spawn so it's only at the edge of the town. OPFOR cannot see them from there.

**Comment by RandAlThor1** [comment]
QA feedback

- The popup for soviet forces being below 8 keeps getting trigged every few seconds.

**Comment by Salamiboio** [comment]
Added another trigger that will detect when Soviets are under 8 people left and then will delete itself. Fixed the issue.

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
