### PR TITLE
Geek_PowerStation_Breakthrough

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:
Add the mission Geek_PowerStation_Breakthrough made by Geek-x to the repository.
It will also add an objectives layer to the Arland and Eden Mission Templates.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [ ] USSR
- [x] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

OPFOR - Attacking
- [x] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

INDFOR - NA
- [ ] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

**Objectives/Win Conditions:**
BLUFOR: prevent opfor from reaching objective.
OPFOR: reach objective.

**Terrain:**
Zimnitrita

**Short mission description:**
OPFOR attempts to remove BLUFOR from a hilltop power station within the time limit.

**Slotting Ratio:**
BLU 2:3 OPF

**Time limit:**
40 Minutes

**Mission Briefing Screenshot:**
image

**Other Notes:**
- OPFOR has 1x BTR.
- Objective is a small radius inside of the power station only.
- Mines are dotted outside play area.

### CODE REVIEW

**Comment by Geek-x104** [comment]
wait one, adding mission config file now

**Comment by Geek-x104** [comment]
testing this now

**Comment by Geek-x104** [comment]
Everything seems to still work apart from the trigger at the end not popping the announcement.

**Comment by RandAlThor1** [comment]
QA Feedback.

- Make sure the "asset" brief indicates who get the asset, even if its kinda obvious.
- its possible for blufor to see opfor spawn from the powerplant (see image, I spawned the BTRs to indicate spawn area)
- opfor slotting screen makes no sense (see image 2)
- change both blu and opfor to have the normal 1-1, 1-2, 2-1, 2-2 ect numbering just to make viewing the groups easier (especially opfor)
image
image

**Comment by Geek-x104** [comment]
- im fixing slotting screen now 
- asset brief can now only be seen by opfor
- will try fix spawns

**Comment by Geek-x104** [comment]
also changed HAT team to LAT team now the HAT char weapons dont exist

**Comment by Geek-x104** [comment]
moved spawn out of LOS

**Comment by Geek-x104** [comment]
@RandAlThor1 anything else you need me to do?

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
