### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by tanaaKa**
**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [x] US

OPFOR - Attacking
- [x] RHS_RF_MSV

**Objectives/Win Conditions:**

Defenders must hold a bridge while attackers must secure it

**Terrain:**

Chernarus

**Short mission description:**

Russian mechanized forces attempt to dislodge a US Marine platoon holding a bridge head in Chernarus.

**Slotting Ratio:**

OPF 3:2 BLU

**Time limit:**

60m

image

### CODE REVIEW

**Comment by RandAlThor1** [comment]
How is the respawn wave being handled?

**Comment by tanaaKa** [comment]
Manually with group spawns via zeus. Just something to keep people invested.

**Comment by RandAlThor1** [comment]
**QA Feedback**

- no blu/op for spawn flag.
- you have 92 slots but the mission.conf only lists 75 for both title and max players.

**Comment by tanaaKa** [comment]
I didnt add a spawn flag since BLU is close to the bridge and has bluforce tracking already. OPF has their ss limit and bluforce tracking.

I will update mission file.

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
