### PR TITLE
Add Arleville Breakthrough Mission

### PR DESCRIPTION
**Pull request by Geek-x104**
adds new mission

### CODE REVIEW

**Comment by tanaaKa** [comment]
Feedback:

- Add a defender LOA in the form of blue dots across the AO where they cannot cross **during safe start**. Annotate this in a briefing.
- BLUFOR has two situations. One's a briefing, I think?:
image
- OPFOR has two situations
image
- Harbor is misspelled
image
- Both briefings should be structured in the same order. Order them appropriately.
- For OPFOR, if you're going to have two platoons, you NEED a company command.
- For BLUFOR, having 4 LATs in a team does not make them an anti-tank element. Give them a panzerfaust.

**Comment by Geek-x104** [comment]
Will do all of these tomorrow.

- BLUFOR LAT Team was the group prefab, want me to add the panzerfaust or leave them as is?
- Harbour is how it is spelt in game, will fix with Harbor, apologies.

**Comment by Pi123263** [comment]
Question, does it make sense to have both a 'Win Condition' Entry and an entry for each of the Objectives? Feels like it might be a bit overkill if im seeing it right and leads to there being a lot of briefing entries which you expect the player to read

**Comment by tanaaKa** [comment]
> Will do all of these tomorrow.
> 
> * BLUFOR LAT Team was the group prefab, want me to add the panzerfaust or leave them as is?
> * Harbour is how it is spelt in game, will fix with Harbor, apologies.

Yeah, they're useless if they only have LAT. A rifle squad has LAT and serves the same purpose.

The harbour comment was a joke, but look at this:
image

**Comment by tanaaKa** [comment]
> Question, does it make sense to have both a 'Win Condition' Entry and an entry for each of the Objectives? Feels like it might be a bit overkill if im seeing it right and leads to there being a lot of briefing entries which you expect the player to read

Win conditions are unnecessary now as well, yes. They were added prior to objectives creating a mission description/brief. Remove those.

**Comment by Geek-x104** [comment]
Copy, will do.
Will leave the spelling of harbour as is so it can be directly correlated to the map label for the objective.

**Comment by Geek-x104** [comment]
hold on this, player count is incorrect.

**Comment by Geek-x104** [comment]
fixed

**Comment by tanaaKa** [comment]
- Remove OPFOR safestart border and tell them to stay in spawn until ready up.
The borders are directly visible to each other if both teams move to them during safestart lol

- Reduce mission timer to 45mins. Attackers are motorized and shouldn't have a problem moving 1KM in 45mins. 60 mins is too much imo.

**Review by tanaaKa — APPROVED** [review]

**Pull request merged**
