### PR TITLE
[Mission] Morton Assault

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:

Add the mission Morton Assault made by Geek-x to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [x] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - Attacking
- [x] USSR
- [ ] RHS_RF_MSV

INDFOR - NA
- [ ] FIA

**Objectives/Win Conditions:**
BLUFOR: Stop OPFOR from destroying 2 portable generators in Morton.
OPFOR: Destroy 2 of BLUFORs portable generators in Morton.

**Terrain:**
Eden/Everon.

**Short mission description:**
Soviet forces move to assault US Army forces in the town of Morton to destroy 2 portable generators.

**Slotting Ratio:**
BLU 2:3 OPF.

**Time limit:**
50 minutes.

**Mission Briefing Screenshot:**
image

**Other Notes:**
Admin Notes: Try and give BLUFOR some time to move around their Safe Start AO as they will need to take up defensive positions

Extras: also updates Eden Mission Template.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
QA Feedback|

- Bombsites are too closer together, 90% of the AO has no reason to be used.
- Sniper and medical teams aren't really needed here
- in the objectives brefing for opfor its "generators" not "detonators"
- I'd say put one of the bomb sites somewhere elese like the below shack just to give the AO a more interesting reason to be used
image

**Comment by RandAlThor1** [comment]
QA Feedback

- snipers? why?
- the 1980s HAT prefab doesn't exist. (of course we just added mods that will likely readd it) you don't need it anyways.
- This way this is described makes it feel like a special. which is FINE, but I don't believe its supposed to be.
- this mission doesn't need so many assets, trim it down.
- some of the scripting text needs a once over.

Overall If you told me this was a gamemode for specials that would be fine, it has the framework of normal missions but the concept of the "bomb backpack" is a tad to much nonsense for me to allow it in CFC missions

**Comment by Geek-x104** [comment]
the generators in the briefings is on purpose as its the portable generator prefab.

**Comment by RandAlThor1** [comment]
it was typo'd iirc as detonators instead of generators

**Comment by Geek-x104** [comment]
ah alright

**Comment by Geek-x104** [comment]
updated admin notes in the top message

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
