### PR TITLE
Add Mission: Geek_City_Assault

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:
Add the mission City Assault made by Geek-x to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Attacking
- [x] US
- [ ] UK
- [ ] RHS_USAF 
- [ ] CDF

OPFOR - NA
- [ ] USSR
- [ ] RHS_AFRF

INDFOR - Defending
- [ ] FIA
- [ ] RHS_ION
- [x] TALIBAN

**Objectives/Win Conditions:**
BLU: Destroy bomb site.
IND: Defend bomb site.

**Terrain:**
Fallujah

**Short mission description:**
US forces assault a Taliban controlled city block to destroy two generators

**Slotting Ratio:**
BLU 3:2 IND

**Time limit:**
50 minutes

**Mission Briefing Screenshot:**
Coming soon.

**Other Notes:**
Admin Note: there are 2 strykers due to them being slightly bugged on hills and other dodgy terrain and is there in case the first stryker gets arma'd.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
**QA Feedback**

- you don't need these extra markers, the gamemode creates its own
image
- we need a general situation
image
- the objectives shouldn't have their own briefing tab (make them not visible to any faction, but keep faction key)
image
- taliban callsigns are messed up
image
callsign group format needs to be changed to just %3 i'll put out a general fix in a second
image
- both spawn flags are sideways 
image
- you have taliban spawning in walls, remember squad formations are great for cleaning them up
image
- both of the bombs are in rooms/places that would IMO better suit the normal bomb prefab, it makes it easier for attackers to find
- you have two strykers but only one crew 
image
- remove one squad for each US platoon and add the extra crew. this will also bring the overall ratio closer to 3:2
- just to clarify you intend to make the US GI walk? you have 28 total vehicle slots for passengers. probably add trucks, or something better to close the gap.
- admins will fix it if it gets bugged out 
image
- these humvee varients need to be spawned in via script. lamentin limbo has a very good script exmaple ('i'd probably also have the strykers via script just to be safe)
- given how much they need to walk, and the overall distance. 50 minutes is not long enough.  
- remove the "objective -" part of the text
image

**Comment by RandAlThor1** [comment]
also, please actually fill out the PR Template, I use it to make the AAR posts

**Comment by Geek-x104** [comment]
> also, please actually fill out the PR Template, I use it to make the AAR posts

Completely forgot, doing it now and will do changes tomorrow.

**Comment by RandAlThor1** [comment]
**QA Feedback**
- callsigns are 1-1 not just 1 ect
image

- blufor callsigns are off
image

- please put your groups into rows or columns, it makes mission start alot less messy, and makes people less likely to accidently or otherwise kill AI. both IND and BLU
image

- honestly, give INDFOR some civ cars. the vanilla ones work fine and they spawn without the need for a script. useful to give them transportation options given the size of the city.

**Comment by RandAlThor1** [comment]
Update the mission.conf with the updated player count and remove the (day)
image

**Comment by RandAlThor1** [comment]
**QA Feedback** 

- indfor needs more cars

- still need to update the config for player count, have 112 slots not 128
image

**Comment by Geek-x104** [comment]
also, added some prefabs for the base game field hospital without the medical trigger thing (forgot what it's called but basically it's missing everything interactable with it) and an the base game arsenal prefab without the boxes (so just the metal bits basically)

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
