### PR TITLE
Add port attack

### PR DESCRIPTION
**Pull request by Geek-x104**

### CODE REVIEW

**Comment by tanaaKa** [comment]
- Important notes doesnt contain anything
image

- Situation should be background information, not a synopsis
image

- Callsigns are wrong on BLUFOR and OPFOR
image

image

Reassign them appropriately in the layer and verify your callsigns in fac manager.

- Bomb site markers should be light green
image

- Rotate BLU spawn marker 90 degrees counter clockwise
image

- Move BLUFOR spawn west to the lutley farms field
image

image

- 30 mins is a bit short. I feel like 35/40 is best. 40 to be on the safe side.

**Comment by Geek-x104** [comment]
ensured BLU and OPFOR were in the correct order.

**Comment by tanaaKa** [comment]
- Slotting still screwed

image

image

Faction manager looks fine, so its the layers.
image

image


Group the managers like I said before. Open up one of my missions if you need an example.

**Comment by tanaaKa** [comment]
Looking good. Last small things then I'll approve:

- M113s are 2 man crews, not 3.
- M113s are in the ground. Click on them and press Ctrl-Shift-Down Arrow to align them normally to the terrain. 
image

**Comment by tanaaKa** [comment]
ALSO, damn I didn't even think of this, but modern marines aren't going to use M113s.

Give them strykers or something else.

**Comment by Geek-x104** [comment]
on a note, there might be a problem when it comes to merging as i accidentally pushed a resourceDatabse.rdb file when uploading my first load of updates from feedback

**Review by tanaaKa — APPROVED** [review]
LGTM

**Pull request merged**
