### PR TITLE
[Mission] {geek} beauregard breakthrough

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:
Add the mission beauregard breakthrough made by Geek-x to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [x] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - Attacking
- [x] USSR
- [ ] RHS_RF_MSV

INDFOR - NA
- [ ] FIA

**Objectives/Win Conditions:**
BLUFOR: stop OPFOR from reaching Beauregard Harbour
OPFOR: Reach Beauregard Harbour

**Terrain:**
Arland

**Short mission description:**
Soviet Forces move to secure the Harbour near Beauregard and dislodge US Army forces in the area who are attempting to stop the soviets.

**Slotting Ratio:**
OPF 3:2 BLU

**Time limit:**
45 Minute Time Limit

**Mission Briefing Screenshot:**
image

**Other Notes:**

*Spawn for OPFOR:*
2x btr-70
1x Medical Vehicle

### CODE REVIEW

**Comment by RandAlThor1** [comment]
QA Feedback

- we've been getting alot of feedback about AO's being too narrow, please expand it similar to this. also when the AO is larger mining the border is far less important.
image
- after you expand it add a opfor LOA, can be really close to their spawn. its mostly a matter of having a clearly defined line.
- opfor coy and plt have the wrong callsign 
image
- (2-mg) implies that there is a 1-mg change it to just MG Team
image

**Comment by Geek-x104** [comment]
will do this tomorrow

**Comment by Geek-x104** [comment]
image

**Comment by Geek-x104** [comment]
feedback*

**Comment by Geek-x104** [comment]
Screenshot 2024-07-11 130640

**Comment by RandAlThor1** [comment]
QA Feedback

- OPFOR coy and first platoon still have the wrong callsigns
image
- used the wrong markers for the blufor LOA
image

**Comment by tanaaKa** [comment]
Requesting 1MG be `MMG` as well please.

**Comment by Geek-x104** [comment]
ok can do not right now tho

**Comment by Geek-x104** [comment]
actually prolly not today so might not be done for mod publishing, sorry

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
