### PR TITLE
[Mission]Manufactured Death

### PR DESCRIPTION
**Pull request by Pi123263**
This Pull Request will:

Add the mission Manufactured Death made by Pi to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [ ] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)
- [x] CDF

OPFOR - Attacking
- [x] USSR
- [ ] US
- [ ] RHS_RF_MSV
- [ ] RHS_US_USMC
- [ ] BUNDESWEHR (US)

**Objectives/Win Conditions:**

Blufor: Defend factory complex
Opfor: Clear out factory complex

**Terrain:**

Myccano

**Short mission description:**

CDF (Blufor) are holed up in a factory complex with 2 platoons worth of infantry, a MAT team and a bunch of static weapons (mainly MGs) and have to defend it to the death, Soviet forces have to attack with 2 Platoons of Infantry and one transport Mi8 and kill the CDF forces.

**Slotting Ratio:**

Blu 2:3 Opf

**Time limit:**

60

**Mission Briefing Screenshot:**
image

**Design concept/thoughts:**

Its a simple mission similar to the powerplant and port attack/defense

**Other Notes:**

N/A

### CODE REVIEW

**Comment by tanaaKa** [comment]
Nothing wrong with a simple mission, but we are trying to get away from simply telling defenders to "defend" without an objective or gimmick.

For example, defenders may need to build defenses if you want them to have a gimmick.

Or, give them an objective, like a logi team needs to extract supplies.

**Comment by Pi123263** [comment]
I was hoping to do a boat extract kinda based objective, however I dont think we dont have any in the modpack anymore at the moment so I cut that part

**Comment by Pi123263** [comment]
Hmm I could try basing an objective around an arty gun, however since they're mostly direct fire at the moment it propably wouldnt work great

**Comment by RandAlThor1** [comment]
QA Feedback

What tanaka said, their needs to be bigger goals for BLUFOR to accomplish here other then just survive 

- make the border markers more dense aka add more. its hard to tell where it is on the map.
- if we have a 2:3 ratio make sure the lobby counts roughtly reflect that, you want closer to 60 OPFOR slots.
- Please seperate game logic with gameplay objects ( see image)  its just impossible to follow and frankly a mess.
- start OPFOR farther away.
- when a mission is using an air landing such as this, you don't need to include the attackers spawn as part of the game area, the game area is used to dictate where they can land and take offensive action from.

image

**Comment by RandAlThor1** [comment]
QA Feedback,


- still need to increase OPFOR count to around 60 to meet the 3:2 ratio
- Mission still needs more depth then just "defend"
- CDF squadleads spawn in the water somewhere, I can't find them
- not your fault but often these static turrets don't work on the server, be prepared to give BLUFOR some other means replace them, hopfully we can get MG teams for CDF. I will test this on the server later.

image

**Comment by Pi123263** [comment]
Yeah I'm tinkering on adding more depth, havent figured out a good objective yet and wanted to get the first few fixes out already

**Comment by RandAlThor1** [comment]
> Yeah I'm tinkering on adding more depth, havent figured out a good objective yet and wanted to get the first few fixes out already


Just a future note, if you don't want me to do a full QA pass. make a note of what has not been fixed.

**Comment by Pi123263** [comment]
okii gotcha

**Comment by Pi123263** [comment]
I added what was fixed to the commit description, I'll just throw a note of that and what hasnt been fixed to the thread as well next time

**Comment by Pi123263** [comment]
Since I cant implement it at the moment here's my current idea for more depth:
Add a VIP slot to Blufor (defenders), the VIP has to stay in the factory complex area for the first maybe 20? minutes, to possibly give opfor time to attack him there, and after that timer runs out he has to be exfiltrated to a location outside of the complex

I'm also tinkering with a new gamemode/altered variant of S&D but thats gonna take a while longer to work

**Comment by Pi123263** [comment]
Added the VIP element to add more depth, as mentioned in the discord the popup doesnt work right yet (not in the version in this pr to avoid bugs), the mission is ready to be played but admins would have to set the time that the VIP is allowed to start moving in some other way (ingame time, irl time, x minuts after safestart, etc.)

**Comment by RandAlThor1** [comment]
@Pi123263 do you have any plans to update this?

**Comment by Pi123263** [comment]
Yes, both havent had time yet due to work/events and hoping for more stuff to be fixed after 1.2

**Comment by RandAlThor1** [comment]
@Pi123263 its has been a month, any chance your gonna finish this?

**Comment by Pi123263** [comment]
Are the relevant bugs fixed now? Then I should have time again soon to finish it up

**Comment by RandAlThor1** [comment]
> Are the relevant bugs fixed now? Then I should have time again soon to finish it up

CDF has been rebuilt and we have ways of getting turrets to spawn without issue.
let me know if you plan on finishing this, if not I would like to remove it from the PR list

**Pull request closed without merging**
