### PR TITLE
Add mission CRF_TVT_125_BlackHawkDown to the mission pool

### PR DESCRIPTION
**Pull request by FluffSquirrel**
Mission Pull Request Template

This Pull Request will:

- Add the mission Blackhawk Down made by FluffSquirrel to the repository.

- Add 3 new FIA characters (Sniper, Radioman, Scout) to the available list (see bottom)

- Add 2 ruined blackhawk models from Project r3dline (already a dependency) required for mission

- Make changes to FIA kits to fix issues encountered in last weeks Spetsnaz (see bottom)

**Mission Creation Checklist:**

- [x ] Mission File
- [ x] Ingame Play Area Markers
- [x ] Ingame Briefings to all players
- [x ] Side-based briefings
- [x ] Objective Entities
- [ x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [ ] US
- [ x] RHS_US_USMC
- [ ] CDF

OPFOR - NA
- [ ] USSR
- [ ] RHS_RF_MSV

INDFOR - Attacking
- [ x] FIA

**Objectives/Win Conditions:**

Locate the heli wreck and retrieve and return the valuable asset to base
Eliminate a predefined (15 for USMC, 10 for FIA) number of enemies
Extract and return friendly forces to base

**Terrain:**

Chernarus Reforged

**Short mission description:**

US Marines and FIA guerillas race to be the first to locate a Blackhawk helicopter crash site and retrieve a stolen valuable asset.

**Slotting Ratio:**

<3:2> INDFOR:BLUFOR

**Time limit:**

<100min>

**Mission Briefing Screenshot:**
Common brief:
image

US brief:
image

FIA brief:
image

**Design concept/thoughts:**

The idea was to take the nighttime forest fights that people have generally expressed being worn out over and put a twist on it to make them interesting again. The mission is pretty akin to last weeks Spetsnaz mission, but the mission starts just before daybreak. This will hopefully create an interesting dynamic where BLUFOR is pressured to move fast to locate the helo before daytime comes when the advantage of their NVG's wears off and they are overrun by the numerically superior FIA.

**Other Notes:**
Vic assets
*note: not sure about vic balancing yet. i want most of the FIA to be relegated to being on foot, the search zone is closer for them anyways. not sure if 2 m2 humvess is op or not, for now since its mostly forest i think its fair. also not sure if FIA should have a ZU-23 Ural. I want the US to play conservative with the helo, but FIA already has up to 10 AT guys so that alone might be enough.

US:
1x UH-1H huey
2x M1025 (M2HB) humvees
1x Maxi M997 ambulance 
1x M923A1 transport truck
4x softshell M998 humvees

FIA:
1x Ural4320 Transport (Civilian)
1x UAZ469 (UK59 LMG)
1x UAZ469 (Unarmed, FIA variant)
1x UAZ452 Ambulance
1x Ural4320 (ZU-23 AA)

final notes: PL's and Squad leads on both sides *need* to be aware of the time. For example if US doesnt realize that day will come soon after opstart, they might take their time too much and be overwhelmed.

Yes, i am aware that both side have different search zones, and it is intentional

The ZU-23 truck hasnt been pre-spawned in like the rest of the vics. Couldnt find it.

The Project r3dline blackhawk wreck only came as a .xob. This means it has no colliders, so you could walk and shoot through it. I made custom "colliders" by inserting brick walls inside of the heli under the outline. This was mostly effective, however you are still able to get inside of the cockpit. Thought i would mention it.

image

--------------------------------------------------------------------------
*FIA KIT CHANGES*
1. B12 binoculars given to PL
2. B8 binoculars given to SL and Scout
3. Extra rocket given to RAT
4. New kits added: Scout, Sniper & Radio operator

### CODE REVIEW

**Comment by Njpatman** [comment]
need to up the playable slots to 128

**Comment by FluffSquirrel** [comment]
> need to up the playable slots to 128

does it need to be exactly 128? is 120 slots enough? i could add another US infantry squad and 3 fia cells, if these squads somehow get filled i imagine gm could just spawn some vics for them. if absolutely needed though i can squeeze in 8 more.

**Comment by tanaaKa** [comment]
> need to up the playable slots to 128

Is there a reason why?

**Comment by Njpatman** [comment]
> > need to up the playable slots to 128
> 
> does it need to be exactly 128? is 120 slots enough? i could add another US infantry squad and 3 fia cells, if these squads somehow get filled i imagine gm could just spawn some vics for them. if absolutely needed though i can squeeze in 8 more.

120 is fine, we just had 82 players 2 sessions ago and don't want to hit a limit/not be able to play this mission if we get more than 86 (@tanaaKa)

**Comment by FluffSquirrel** [comment]
> > > need to up the playable slots to 128
> > 
> > 
> > does it need to be exactly 128? is 120 slots enough? i could add another US infantry squad and 3 fia cells, if these squads somehow get filled i imagine gm could just spawn some vics for them. if absolutely needed though i can squeeze in 8 more.
> 
> 120 is fine,

sounds good, will throw in the extra slots. going to leave the vics as is for now. all that would really be needed though if it fills is more blufor unarmored humvess even though theres overhead past 86 slots anyways. appreciate it.

**Comment by RandAlThor1** [comment]
QA Feedback

Thank you for making a mission!

-------------
Objective issues

- I don't hate the objectives. but something feels off about "kill at least 10 USMC/15 FIA" but its been a very long time since we've done a mission like this. so I'm curious to see how it plays out.

---------------------

it feels like you threw the everything and the kitchen sink in this mission

- what does recon do here that everyone else doesn't? 
- blufor doesn't need two jtacs, infact that will likely cause alot of overstep.
- the USMC squad structures you are using are built around using 2 unarmed and 1 armed humvee each, probably should give them that
- it doesn't work, but if you had a ZSU you would want a dedicated team for it.

- I'm thinking removing the recon teams from both sides. and solidifying what assets are for each team would help with the focus alot here, right now its hard to tell how you want either side to approach this objective.

-------------

Lobby issues

- Win Conditions are side specific yet are visible to everyone. Change win conditions to provide both sides exact win conditions so both leaders know what is going on
image

- Merge the asset tabs and make them universal, we don't want suprise assets for either side, and Admins are gonna have to spawn vehicles in due to technical issues.

- FIA has 10 squads/cells and a recon team under a single platoon lead. that's gonna be hell for plt. add a company element and 2nd platoon element to spread out the leading.

- Both sides recon teams need to go on the bottom of their respective command. in this case, on the bottom of their roles. (this is a general rule with any specialty slots)


------------
Technical notes

- im going to go and add NVGs to all of the USMC loadouts because the risk of them disappearing and ruining peoples experience is not something I want to take.

- thank you for making those changes to FIA they look good to me, for future reference can you please make those a seperate PR. makes it alot easier to keep them in focus. love that you did them tho thank you.

- for future reference a "mission briefing screenshot" looks more like this, it helps us see the AO and we use it for posting the AAR for the weeks missions.
image

- the ZSU-23 mod has been removed from the workshop afaik, gonna have to find a replacement for that. as long as the Huey is unarmed. you don't really need to provide strong AA, as its mostly a mobility/recon asset and not a lethal one.

- some vehicles cause missions to not load, this is a reforger issue. reference this message: https://discord.com/channels/237991125523103747/468879945293234177/1258809499750240407 Remove the needed vehicles and they will be added back by admins on mission start, just make sure the notes in here and the Asset briefing are accurate to what is needed.

**Comment by FluffSquirrel** [comment]
> QA Feedback Feedback
> 
Alright you put a lot in here so im just gonna go 1 by 1 for everything. 

Objective issues:
Without this objective, there isnt any guarantee that one lucky squad wont just find the helo and end it there. Maybe another objective can be used, but i think mine works because even if that lucky squad finds it, any contact that is made wont just be broken off in order to end the mission. It just makes 100% sure that some combat will happen.

Kitchen sink issues:
1. Yes i did throw near everything in here. Its my first Workbench mission and wanted to get a feel for everything so i can use it in future missions.

2. The recon is there for two reasons. To give more slots and to provide a break from every single squad being straight infantry. So no, they really have no use and could just be replaced.

3. Not sure how yall use JTACS in op and what their role is. Will just take one out of BLUFOR recon.

4. regarding the humvees, can do. im maybe mildly concerned about too many M2 hummers. Might think about it some more

5. Alright, ill just scrap it. Will take it off of asset list and such. FIA has got 10 rpg guys, thats AA enough in itself.

6. Honestly dont really understand what you mean. Maybe im just thick . Im down for removing recon but im not sure if i just want it to be straight infantry vs straight infantry. I want to get some specialties in the somewhere if its gonna have 127 slots.


Lobby issues:
1. Not on the world rn and cant open it, but i thought both side have faction specific win conditions? if not i will add them. I assume the main thing would just be the 10/15 difference  because the other two OBJs are the same. I understand why it could be vague though. 

2. Can do

3. Never thought about a company size force, will add and should be fun to tinker with. Might make some new squad comps for it.

4. think i understand this one, can do


Tech. notes:

1. Go ahead, for now i will leave the box though.

2. Got it with the seperate PR, will do in the future. Just to make it known the radios are still fucked, i never played with them.
I honestly think the whole relaying messages thing we had to deal with in Spetsnaz could be fun, it was just so frustrating because i specifically remember Tanaka saying the radio ranges were fixed before the op so we didnt plan for it, then we got in and they werent. If the FIA knew before hand that their radios only had a 1.2km range or whatever, it could actually be a lot of fun if allowed to plan for it.

3. Got it, sorry bout that

4. Yeah was kind if thinking that anyways, like i said earlier just gonna can it.

5. Yeah i thought i remembered that, but i saw them in Tils mission and they were loading fine in localhost so i kept them. Will remove.


Thanks big time for looking at my wonky ass mission and letting me know all the messed up stuff. Should have everything fixed in the next 24hrs. Thanks again

**Comment by FluffSquirrel** [comment]
> QA Feedback

Most everything should be fixed up now and ready for another QA pass. Will provide a list below of the changes I can remember. I made a lot of new FIA kits and put them in the mission, but won't include them in this PR for now.
------------------------------------------------------------------
-FIA is now a company size element, with company command, two platoons, both consisting of 3 light inf cells, 1 heavy inf cell, and a support cell
-Both sides have had recon team removed, but BLUFOR now has a MMG team to replace them
-All vics have been deleted
-Win conds list made side specific, then merged with Objectives list
-Assets list now factionless
-Implied before but 2nd BLUFOR JTAC now gone
-Radioman added to FIA Company Command
-Extra M998 given to BLUFOR
-ZU-23 Ural4320 removed from FIA Asset list
-All squads now properly ordered
-----------------------------------------------------------------
Notes:
-Dont really want to give all US squads 1x M2 1025 and 2x M998. For now whole company has 2x M1025 & 5x M998
-US Arsenal box is still there with the NVG's. I will leave it there for now. If you add NVG's to all USMC kits it should hopefully be redundant, because I believe i only made custom kits for FIA. Just a failsafe.

**Comment by FluffSquirrel** [comment]
> I made a lot of new FIA kits and put them in the mission, but won't include them in this PR for now.

well now that i think about it I might need them to be included so it doesnt break

**Comment by RandAlThor1** [comment]
haven't looked yet, but yeah if you have character prefabs assigned to groups in the mission, they kinda need to be included in this branch.

**Comment by FluffSquirrel** [comment]
> haven't looked yet, but yeah if you have character prefabs assigned to groups in the mission, they kinda need to be included in this branch.

oopsie daisies
should i make a new PR or what. the new character prefabs are:
MG (UK59L)
MG Assistant (UK59L)
Automatic Rifleman (RPK74)
Assistant AR (RPK74)
Rifleman [current CRF rifleman has demo charges]
Ammo Bearer
Medium AT (RPG7)
Med. AT Assistant (RPG7)
Light AT Rifleman (M72 LAW)
Sapper (3x demo charge 1x AT mine)

I might have you put a hold on the QA runthrough because I feel like clogging up the framework with these redundant kits really isn't necessary unless youre alright with having 3 types of AR and shit. I can take them out and simplify them though.

**Comment by RandAlThor1** [comment]
I assume these are all for FIA, feel free to bring them into this. once your mission gets brought into release I'm going to go through and organize things for myself

**Comment by FluffSquirrel** [comment]
> I assume these are all for FIA, feel free to bring them into this. once your mission gets brought into release I'm going to go through and organize things for myself

Done. Yeah you will have to organize them some, mine will make some CRF ones redundant, all of mine have the _BD suffix which will need to be removed. You should probably also change the name of the current PKM gunner and his assistant to Machine gunner instead of autorifleman for parity. (Or the UK59 and assist to AR. IDK)

good for a QA pass now though

**Comment by RandAlThor1** [comment]
QA Feedback
-----------
FIA Loadouts/groups
Reference: https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?gid=1049962237#gid=1049962237

I'm not against people making their own character loadouts. but I fail to see the reason behind alot of these.
-what is gameplay benefit of operating the RPK/PKM/UK59L in the same platoon like this? either you want the RPK over the PKM, or the UK over the PKM why all three?

- Plt isn't 1-1, 1-1 is labeled as both 1-1 and 1-2, company is also labeled as 1PLT
image
- your AARs are missing the bino's
- why does the "light" cell have an MG
- using the RPK is fine, it was determined that people wanted the PKM as the RPK consistently underperformed to its blufor equivalents
- what is a sapper if not a rifleman demo? which you removed just to replace with the same thing?
image
- what is a scout if not just a rifleman, also they have invalid stuff in their inventory
image
- how does this differ from our already existing SL, same goes for PL
image
- you recreated the RAT just to give them an extra rocket that was removed, OPFOR has too many rockets especially when they have AAT
- if your gonna call the UK59 user and MG in game, call the slot one, they are also VERY low on ammo, rocking 350 rounds on his person when the expected minimum is 400. preferably closer to 600
- your MAT is literally identical to your RAT, this tends to be why we don't have mat/lat teams in current reforger. lack of AT options that actually make a difference
- radiomen serve zero function in current reforger, the issue with radio range was FIA not having the correct radios.
- the sniper is missing alot of ammo, should have around 120 shots not 50
- who is the ammoBearer supposed to bearing ammo for? their backpack is empty.
- LAT has the same issue as the scout
image
- you don't just number them like this, as the factionManager is used to display the squads icon/name on the map
image

-----
BLUFOR
- MG team needs to be below the Riflesquad
- fix the naming same as for FIA
-  the reason each squad had a 50.cal humvee is because 3 unarmed humvees cannot carry the entire squad 4*3 =/= 13. ether replace one of the unarmed humvees with an armed one, or decide on a different form of transportation for the squads.
---- 
Technical

- briefing changes seem good.

**Comment by FluffSquirrel** [comment]
> I'm not against people making their own character loadouts. but I fail to see the reason behind alot of these.
-what is gameplay benefit of operating the RPK/PKM/UK59L in the same platoon like this? either you want the RPK over the PKM, or the UK over the PKM why all three?

i dont fucking know. ill cut the rpks

> Plt isn't 1-1, 1-1 is labeled as both 1-1 and 1-2, company is also labeled as 1PLT

cannot figure out how to do the callsigns manually through faction manager for the life of me

> your AARs are missing the bino's

will fix

> why does the "light" cell have an MG

 i mean, maybe just a design choice, but they are comparably "light" to the CRF fia cell, with their pkm and MAT vs the light cells LAT

> using the RPK is fine, it was determined that people wanted the PKM as the RPK consistently underperformed to its blufor equivalents

fia has a big numerical advantage and positional advantage so i dont want blufor to be overwhelmed by 10 PKMs with 800 rounds each

> what is a sapper if not a rifleman demo? which you removed just to replace with the same thing?

i mean i guess they have an AT mine too? i also edited it myself to fix the issue with demo blocks not spawning, by changing it to the editable demo block. its just a fixed and renamed version  of the demo rifleman
-- coming back later now, i remember i did it because CRF framework has no basic rifleman. it only has the demo rifleman .

> what is a scout if not just a rifleman, also they have invalid stuff in their inventory

theyre redundant and i forgot to remove my fault

>how does this differ from our already existing SL, same goes for PL

they have the fixed binos and shit

> you recreated the RAT just to give them an extra rocket that was removed, OPFOR has too many rockets especially when they have AAT

in Spetsnaz my AT guy had 1 rocket (none in his backpack) with no AAT. I thought that i fixed it, but maybe somethings wrong with it. ill take a look and go back in to it. for my own uses, its enough rockets because 8/10 cells dont have RPGs in the first place

> if your gonna call the UK59 user and MG in game, call the slot one, they are also VERY low on ammo, rocking 350 rounds on his person when the expected minimum is 400. preferably closer to 600

i referenced the charts and i thought i gave them enough but i probably fucked it up. ill go back and fix it

> your MAT is literally identical to your RAT, this tends to be why we don't have mat/lat teams in current reforger. lack of AT options that actually make a difference

im assuming that RAT is rifleman AT, but i dont have a rifleman AT? I have a LAT character and a MAT character, so im lost as to what youre referring to

> radiomen serve zero function in current reforger, the issue with radio range was FIA not having the correct radios.

 alright well if its fixed then i will cut them out of Comp command and remove the character prefab
 
 >the sniper is missing alot of ammo, should have around 120 shots not 50
 
 will fix 
 
>who is the ammoBearer supposed to bearing ammo for? their backpack is empty. 
 
 i put shit in their backpack not sure why its not showing for you.
 
 > LAT has the same issue as the scout
 
 will fix
 
 > you don't just number them like this, as the factionManager is used to display the squads icon/name on the map
 
 i couldnt figure it out at all man, dont know what to do with it

> MG team needs to be below the Riflesquad

will try and fix some weird issue where the MG team stays above the rifle squads in the heirarchy even though i named it z_mgteam. it works on local host though so idk

> fix the naming same as for FIA

ok

> the reason each squad had a 50.cal humvee is because 3 unarmed humvees cannot carry the entire squad 4*3 =/= 13. ether replace one of the unarmed humvees with an armed one, or decide on a different form of transportation for the squads.

fair. i have it in my head that the squads are 11 men cause thats what show up in the world editor. can give m2 to each.

-------------------------------------------------------------------------------------

at this point i can just scrap the mission if theres too many issues, seems like im moving backwards from the first QA pass and not too sure about it anymore.

thanks for your time sorting through it again

@RandAlThor1

**Comment by RandAlThor1** [comment]
I don't think the mission has too many issues, I think you tried to reinvent the wheel with your loadouts and squad layouts. thats literally 90% of the QA feedback. 

we have existing group layouts that are tested and good, and absolutely FIA was missing plenty of them, but you need to take a step back and understand what your getting into when you decide to create character and groups prefabs while also creating your first coalition mission.

**Comment by FluffSquirrel** [comment]
alright list of changes
-removed radioman from fia company HQ

-fixed callsigns and ordering for both factions (thanks hittheman)

-removed 1 rocket each from FIA MAT & MAT Ass. for a total of 4 coming from 6

-deleted FIA radioman and scout character prefabs because theyre useless now

-removed some shit related to the old callsigns in notes

-b8 binoculars added to rpk assistant, uk59 assistant, pkm assistant. PKM ass. doesnt have a new prefab because (and you told me this earlier but i didnt realize) i can edit their loadout for the mission. i thought since CRF is locked i had to make a new prefab to edit their inventories. _i guess that means i could go in and delete my custom character prefabs that are just fixed CRF ones, but that would mean i have to edit squad comps and all that stuff too. RandAl if you want me to do that just let me know._

-UK59 gunner upped to 500rnds, UK59 ass. upped to 400rnds (of UK59 ammo). 900 per team plus the ammobearers carry a few boxes. 

-LAT invalids fixed

-1x M1025 (m2) and 2x m998 per full squad given to blufor, for 3x m1025 and 6x m998, changed assets list to boot

- FIA ammo bearer kolobok bp contents adjusted.(still not sure why you couldnt see whats in their backpacks)

-FIA sniper buffed to 110 rnds, PM pistol added +mags as well

- RPK in both FIA support squads switched to UK59 

-figured out the issue with the RAT. not sure how it got in there, wasnt supposed to.

------------------------------------
as far as reinventing the wheel, i guess i tend to do that a lot. idk.

**Comment by RandAlThor1** [comment]
QA Feedback

- these briefings are too long people aren't going to read them, alot of this is covered by "situation" and "Objectives" they don't need to be repeated here.
image
image

- your FIA heavy groups are different, one contains a mat one doesn't
- Call the slot, "Medium Anti-Tank" and "Assistant Medium Anti-Tank" not Rifleman (Med. AT)
- I'm still trying to understand what support the "support" cell provides that differ from the other cells. heavy makes sense with a bigger MG and MAT effective being a "weapons" squad. but the support cell is strange.
- your UKL AR has a full backpack and cannot get all of his ammo 
image
- Your ammobearer which again needs to be made more descript. who is he meant to actually be carrying ammo for, and why isn't this just an Assistant Automatic Rifleman. has a full backpack and cannnot insert one of the 100rd boxes.
- and yes, if all your doing is fixing an existing prefab. aka adding Bino's to the SL/PL ect. just change what is already there and not create whole new prefabs just to do that.

**Comment by FluffSquirrel** [comment]
closing pr cause im a dumbass

**Pull request closed without merging**
