### PR TITLE
Mission/geek breakthrough

### PR DESCRIPTION
**Pull request by Geek-x104**
Mission Pull Request Template

This Pull Request will:

Add the mission **St Pierre Breakthrough** made by **Geek-x** to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [x] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - NA
- [ ] USSR
- [ ] RHS_RF_MSV

INDFOR - Attacking
- [x] FIA

**Objectives/Win Conditions:**
BLUFOR: Defend Church from INDFOR
INDFOR: Capture Church.

**Terrain:**
Everon/Eden

**Slotting Ratio:**
BLU 2:3 IND

**Time limit:**
50 min

**Mission Briefing Screenshot:**
image

**Other Notes:**
None rn

### CODE REVIEW

**Comment by RandAlThor1** [comment]
**QA Feedback**

Please check the boxes
image

**Comment by Geek-x104** [comment]
FUCK

**Comment by RandAlThor1** [comment]
**QA Feedback**

- I know I said bigger AOs but jesus christ, too big
image

- damn thats alot of 1st squads
image

- I'm really becoming a very big hater of Breakthrough style missions. do something like make the two towns leading up to main OBJ zones to capture as well, make them worth 25% and the main town 50% so that there is more to the objective and decisions for both sides.

- make the zone in the main town farther back or harder to accidently hit. its kinda in the front.

- give defenders trucks. even after you shrink the AO its still gonna need them.

**Comment by Geek-x104** [comment]
in that case, i'm probably not going to have this out for this friday, will work on it for the friday after.

**Comment by Geek-x104** [comment]
closing, dislike the mission and want to make a new one

**Pull request closed without merging**
