### PR TITLE
add mission CRF_BT109_Traumatic_Trenches to the repository

### PR DESCRIPTION
**Pull request by FluffSquirrel**
Mission Pull Request Template

This Pull Request will:

Add the mission Traumatic Trenches made by me to the repository.

**Mission Creation Checklist:**
- [x ] Mission File
- [x ] Ingame Play Area Markers
- [x ] Ingame Briefings to all players
- [x ] Side-based briefings
- [ x] Objective Entities
- [ x] Mission .conf file

**Faction(s):**
BLUFOR - /NA
- [ ] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - Defending
- [ ] USSR
- [x ] RHS_RF_MSV

INDFOR - Attacking/
- [x ] FIA

**Objectives/Win Conditions:**

Seize 3x command bunkers and the church at the rear of the Russian lines

**Terrain:**

Zarichne

**Short mission description:**

FIA forces will make a full frontal assault across no man's land to reach enemy trenches.

**Slotting Ratio:**

1:3 OPFOR:INDFOR

**Time limit:**

45m

**Mission Briefing Screenshot:**
image

**Design concept/thoughts:**

the mission is kind of a mix between a regular mission and a special. meant to be pretty quick, small AO, very fast paced action, lots of death.

**Other Notes:**

fia has 1x podnos 82mm mortar

there are 4 artillery barrages preplaced on the map. they have to be manually enabled by a gm, but after that will run until mission end without interference. preferably the two north-easternmost ones would be enabled as soon as mission loads, with the other two enabled after safestart. if thats too much a hassle, just enable all of them after safestart

### CODE REVIEW

**Comment by RandAlThor1** [comment]
**QA Feedback** 

- no fake arty, either we have player led arty or we don't have it.
- give opfor the mortar not indfor. attacker mortars in missions like this are not counterable, make them something indfor wants to push towards to kill.
- 3:1 is INSANE, if you want this to be a special im good with it. but we won't play this mission as a regular mission as is frankly.
- if this is a special, start IND for closer to the SW so they get into the action faster, remove OPFORs abilty to go past their trenches to clear bushes ect, and reduce briefing to be something people can get in seconds.
- COY not "1stCOM" 1/2PLT not "1st/2ndPLT"
- clean up INDFORs spawning, you can put them into rows or columns via AIFormationComponent
image
image

**Comment by FluffSquirrel** [comment]
update changeloggggg

went full focus on making it a special
-mortar given to msv
-mortar team added to msv
-mortar team removed from fia
-both sides had callsigns adjusted
-changed mission title to suit new playercount & status as a spcl
-moved fia spawn to the command bunker
-removed opfor safestart border
-removed offmap artillery
-changed up callsign names that were wrong cleared up indofr spawning, new picture here
image
-all briefings shortened, no more fluff, just straight business
-removed a barrel that wasnt loading lods for some reason and was stuck at lod3
-changed AO border
-moved fia spawn mark and safestart border
-moved mortar mark to new spot and made it MSV visible only
-30m timer too

**Comment by RandAlThor1** [comment]
**QA Feedback**

- start the mortar team next to the mortar. move opfor to start closer to the trenches.
- FactionDominance triggers setup like this MIGHT be what caused all of the voip issues last week, I'd be down to test it with a special where we can switch if it is the problem.
- some of the trigger zones are incredibly tiny and in the ground so they are never going to be triggered.
- really tho if this is a special the objective should be simple as hell. just make one objective to storm onto the other side of the trenches. keep it simple as hell

**Comment by RandAlThor1** [comment]
@FluffSquirrel any updates on this?

**Pull request closed without merging**
