### PR TITLE
Fixed issues with missions: Airport Assault and Port Attack

### PR DESCRIPTION
**Pull request by Geek-x104**
- Fixed JIP error (hopefully) by replacing all ai units
- moved port attack bombsites and obj markers around to add variety (haven't changed anything else)

### CODE REVIEW

**Comment by Geek-x104** [comment]
Wait one on this, forgot the group names.

**Comment by Geek-x104** [comment]
fixed

**Comment by tanaaKa** [comment]
Your platoon command has a SL as the PL. Switch out the entity in the group.
image

**Comment by tanaaKa** [comment]
Nvm the above. I added it.

**Comment by Geek-x104** [comment]
That is due to the group entity having an SL as the group lead over the PL.

**Comment by tanaaKa** [comment]
> That is due to the group entity having an SL as the group lead over the PL.

I'm aware, but it's everyone's job to catch these things and fix it. Fixing it in one mission PR will fix it for everyone else.

**Review by tanaaKa — APPROVED** [review]

**Pull request merged**
