### PR TITLE
add Search and Destroy misssion

### PR DESCRIPTION
**Pull request by Geek-x104**
Adds mission files

### CODE REVIEW

**Review by Njpatman — DISMISSED** [review]
All good, awaiting merge from Tanaka

**Comment by tanaaKa** [comment]
@Geek-x104 

Feedback:

- BLU Slotting screen is wrong
image

Place your groups in order of what you want them to be in the BLUFOR or OPFOR layer. Move them all out to the init layer, then drag them back in in order you want the slotting screen to be. This way it matches up with the callsigns from the faction manager too.

- I created and added a gametype brief to your mission

image

- IMO, you should add some roadblocks, mg nest, etc... compositions around the town to make it feel more alive
image

Tons of compositions, bunkers, etc.. that you can place in the world

**Review by Njpatman — CHANGES_REQUESTED** [review]
Amount of playable slots in title is out of date, please update.

**Review by Njpatman — DISMISSED** [review]
Looks good, awaiting push by Tanaka

**Comment by Njpatman** [comment]
resourceDatabase.rdb has a conflict. Pls get rid of the file change

**Review by Njpatman — APPROVED** [review]
good to go

**Pull request merged**
