### PR TITLE
Add 'Russian Secrecy' Mission

### PR DESCRIPTION
**Pull request by Pi123263**
Short Description:
AFRF has to get an HVT (Pilot) to an exfil location across the island, BW forces have to stop them an eliminate the HVT

Assets:
BLUFOR;
Unarmed Transport
Recon Helo (UH-1H)

OPFOR:
Unarmed Transport
APC(BTR-70 edited PIE Variant)
Factions;
BW/RHS AFRF

### CODE REVIEW

**Comment by tanaaKa** [comment]
Feedback:
- Rename the US faction to be "Bundeswehr"
- Change US flag assets to GER flag assets (they're in the BW gear pack dir)
Looks silly otherwise lol:
image

- Fix your PLT group to remove the SL and replace with a PL:
image

- There are no appropriate callsigns assigned. Groups should be 1PLT, 1-1, 1-2, etc...
Specialties should be their shortened names. Anti-tank team: MAT1, etc...

You can add these in the faction manager under callsigns for your appropriate faction. Make sure they're not randomly assigned as well.

- Are the BW attempting to capture the downed pilot? If so, he is not a HVT. He is a VIP or something else. HVT implies kill on sight. Just verifying verbiage. 

- Missing a blufor briefing
- Missing an opfor briefing
- A note should be added to both sides that specifies that a pilot must not change their uniform and is a roleplay position. Very easy to cheese dick that role.
- You should a trigger to check for the pilot at the extract. Otherwise we won't know if he has made it.

**Comment by tanaaKa** [comment]
Oh and I think this mission would be REALLY sick at sundown/dusk with nods assigned to both sides. My 2c

**Comment by Pi123263** [comment]
Any chance you have some pointers for me on how to make that pilot trigger? as in how to check the person in the trigger is actually the pilot? I assume some combination of assigning him a variable name and then checking for that in the code

**Comment by tanaaKa** [comment]
Lacking objective entities and most issues from your other mission

**Comment by Pi123263** [comment]
@tanaaKa Feedback should be incorporated, please re-check

**Comment by tanaaKa** [comment]
- Group order is still incorrect it seems
image

- The callsigns are better, but still not to the A3 standard we had:

Group name (callsign visible on map/group marker/slotting screen)

Company Command (COY)

1st Platoon (1PLT)
1st Squad (1-1)
2nd Squad (2-1)
etc....

2nd Platoon (2PLT)
1st Squad (2-1)
2nd Squad (2-2)

Medium Anti-tank Team (MAT1)
Medium Machine Gun Team (MMG1)

T72B3 Crew (TNK1)
BMP3 Crew (IFV1)
etc....

Not attempting to be pedantic of course, but we need to get back to our A3 standard. I know it's a PITA rn, but I will update the default faction manager to have these.

Also it's okay to have a realistic deviation of these. IE blufor uses the above structure, but opfor goes by:

Platoon Command (IVAN10)
1st Squad (IVAN1-1)
2nd Squad (IVAN1-2)
etc...

- The briefing is a bit rough for both sides. 
image


Can you expand the text in the objective.et and change the title for both to `Objective: Kill Pilot` etc...

**Review by tanaaKa — APPROVED** [review]

**Pull request merged**
