### PR TITLE
Added "Drizzly Mudflats" mission

### PR DESCRIPTION
**Pull request by Til-Weimann**
This Pull Request will:

- Add the mission Drizzly Mudflats made by Til to the repository.
- Add a couple of new group and character prefabs required by the mission (MSV Motor Rifle Platoon, 2020 USMC Rifle Platoon)
- Add BLUFOR and OPFOR game zone variants, name all variants accordingly
- Add easy game zone generators for splines and polylines

**Mission Creation Checklist:**
- [X] Mission File
- [X] Ingame Play Area Markers
- [X] Ingame Briefings to all players
- [X] Side-based briefings
- [X] Objective Entities
- [X] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [ ] US
- [X] RHS_US_USMC
- [ ] CDF

OPFOR - Attacking
- [ ] USSR
- [X] RHS_RF_MSV

**Objectives/Win Conditions:**

OPFOR seizes the objective area

**Terrain:**

Mussalo

**Short mission description:**

Russian Motor Rifles assault an airfield defended by a motorized USMC Rifle Platoon.

**Slotting Ratio:**

2:3 BLU:OP
Up to 104 players

**Time limit:**

60m

**Mission Briefing Screenshot:**

image

The faction briefing is structured a little differently than usual, but this is mostly cosmetic and should not be a problem.

**Design concept/thoughts:**

OPFOR has to effectively use its BTRs to make its way to the airfield, this may include crossing fords or straits. BLUFOR, motorized with HMWVVs, is able to quickly move around the AO, strike and reorient.
There are up to 6 OPFOR squads with 1 BTR-70 each, while BLUFOR has up to 3 large squads with 2 M998s and 1 armed M1025 each.

**Other Notes:**

I tested basic functionality in Play mode

### CODE REVIEW

**Comment by RandAlThor1** [comment]
QA Feedback

- I can appreciate making mission specific character prefabs, these appear to be the RHS defaults with your own stuff. these do not fall in line with our goal of standard loadouts see here: https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?gid=1049962237#gid=1049962237
- many things are wrong with the loadouts in relation to standard, differing ammo counts, weapon types, frag/smoke counts, medical ect. please either bring all of these in line with our standard, or just use our existing group prefabs.

-----------------------------------------------------------

- OPFOR briefings, Execution is empty, Command and signal is pointless. service and support should be a universally available "Asset" note so both sides know what is in play. 
- BLUFOR briefings. largely the same as opfor

-----------------------------------------------------------

- I'm not sold on the location, the area around the airfield is pretty small, and also borders the edge of the map in a not great way.
- you don't need to include if a group is motorized in the lobby but I'm not going to say its a bad thing.
- make sure to edit the faction manager so groups show up as 1-1, 1-2, 2-1, 2-2 ect. instead of things like "Blazer White 1/2/3/4 ect"

-----------------------------------------------------------

- Another note, due to technical issues, vehicles do need to be removed and then readded by a game-master currently in order to get the missions to load. afaik this is still needed for non vanilla maps.

**Comment by Til-Weimann** [comment]
> I can appreciate making mission specific character prefabs, these appear to be the RHS defaults with your own stuff. these do not fall in line with our goal of standard loadouts see here: https://docs.google.com/spreadsheets/d/1cpFU4wZFa2P8NVyqYhY3q3eDcZ1-ZkE5NpPFkasLsGU/edit?gid=1049962237#gid=1049962237
many things are wrong with the loadouts in relation to standard, differing ammo counts, weapon types, frag/smoke counts, medical ect. please either bring all of these in line with our standard, or just use our existing group prefabs.

I created new group and character prefabs because the CRF standard is not suitable for this kind of mission, especially squad organization. The new groups are a USMC Rifle platoon (2020) based on MCRP 3-10A and a standard Russian Motor Rifle platoon.

Squad level vehicles like the BTR just often don't fit together very well with an standard CRF squad.
I inherited character prefabs from RHS since I was not entirely happy with the existing CRF ones, and others were completely missing (for example Russian AR have a PKMs).

I assumed adding another type of squad or character would be okay as it's somewhat relevant and no existing ones are modified - after all, e. g. Rocketeers also uses customs characters.
I will offer to change all character prefabs to existing CRF ones, but not the group prefabs since the standard CRF squads are just not suitable, especially on the Russian side.

> OPFOR briefings, Execution is empty, Command and signal is pointless. service and support should be a universally available "Asset" note so both sides know what is in play.
BLUFOR briefings. largely the same as opfor

Execution is empty intentionally since this would be briefed by the commander. It and command+signal are indeed not necessary, but don't do any harm either, so I added them to complete the OPORD.
Enemy assets are already mentioned in the Situation tab under enemy forces.
Again, I did the briefing this way since I believe it looks better, but if you need me to stick to the standard, I can.

> I'm not sold on the location, the area around the airfield is pretty small, and also borders the edge of the map in a not great way.

I don't think this is an issue. The airfield itself is small, but combat is meant to take place all across the BLUFOR AO, which is large enough. I don't see how the northern map border would matter at all, it is not in the way of anything since OPFOR is attacking from the south.

> make sure to edit the faction manager so groups show up as 1-1, 1-2, 2-1, 2-2 ect. instead of things like "Blazer White 1/2/3/4 ect"

If everything else sounds okay to you after the proposed changes, I will.

**Comment by Njpatman** [comment]
For the character prefabs: 

starting icon only really needs to be set for team leads, it's typically more efficient to let the clients auto-detect their loadouts throughout the mission. Also makes it easier for SLs to just look and see at a glance what the squad has in terms of weaponry.

**Comment by RandAlThor1** [comment]
> I created new group and character prefabs because the CRF standard is not suitable for this kind of mission, especially squad organization. The new groups are a USMC Rifle platoon (2020) based on MCRP 3-10A and a standard Russian Motor Rifle platoon.

realism does not equate fun, our goal is for consistency and I really don't see how our existing squad structures accomplish these mission worse then what you have created.

> Squad level vehicles like the BTR just often don't fit together very well with an standard CRF squad. I inherited character prefabs from RHS since I was not entirely happy with the existing CRF ones, and others were completely missing (for example Russian AR have a PKMs).

Russian AR's getting PKMs is based on community feedback about the poor relative performance of RPKs vs other faction alternatives.
when it comes to BTRs, crews are a separate prefab, tho I do believe they are missing from the current group prefabs for MSV.

> I assumed adding another type of squad or character would be okay as it's somewhat relevant and no existing ones are modified - after all, e. g. Rocketeers also uses customs characters. I will offer to change all character prefabs to existing CRF ones, but not the group prefabs since the standard CRF squads are just not suitable, especially on the Russian side.

creating prefabs is fine, but these prefabs need to match the gear standards we have layed out, as is many slots are low on ammo, have too much 40mm grenades, among other issues. I again fail to see what our existing group structures cannot accomplish that these will. different group prefabs are fine tho and I will not fail a mission because of them, so long as they make sense.

Rocketeers are specifically for a "special" which is a type of mission that is more of a mini game rather then a proper mission.
these can be identified by the "spcl" tag in their prefab name.

>Execution is empty intentionally since this would be briefed by the commander. It and command+signal are indeed not 
necessary, but don't do any harm either, so I added them to complete the OPORD.
Enemy assets are already mentioned in the Situation tab under enemy forces.
Again, I did the briefing this way since I believe it looks better, but if you need me to stick to the standard, I can.

they are messy and frankly add an unneeded amount of tabs that provide little to no information about the mission at hand.
I would much prefer a simple "briefing, assets, objectives, ect" style structure that is more clear

>I don't think this is an issue. The airfield itself is small, but combat is meant to take place all across the BLUFOR AO, which is large enough. I don't see how the northern map border would matter at all, it is not in the way of anything since OPFOR is attacking from the south.

With this many mobile assets, like BTRs and Humvees with 50 cals. combat is goinig to take place over a larger then normal area, as people need to maneuver around these assets. that and with the map border functioning as a sudden pit that can cause people to fall, I don't believe its a non-issue that won't come up.

**Comment by Til-Weimann** [comment]
Removed all character prefabs except 5 standards-compliant ones, which CRF had no equivalent for:
- CRF_USMC_GL (no radio, otherwise identical loadout to CRF TL)
- CRF_USMC_PSG (identical loadout to CRF PL)
- CRF_USMC_TLBLUE (identical loadout to CRF TLs)
- CRF_RF_MSV_VKPO_Sharpshooter (compliant with the spreadsheet)
- CRF_RF_MSV_VKPO_PSG (identical loadout to CRF PL)

Simplified briefing
Disabled vehicle prefabs because of the potential loading issue
Improved callsigns
Renamed mission to "Misty Mudflats"

**Comment by tanaaKa** [comment]
I think it's probably worth meeting to discuss adding more realistic/battle order groups with standardized loadouts for a bit more realistic missions compared to our "balanced" loadouts/groups.

**Comment by RandAlThor1** [comment]
QA Feedback

just little nitpicks now.

Loadout fixes
- USMC_GL needs radio
- MSV_Sharpshooter remove their morphine

------------

- USMC objective description still has the "II." in the title

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
