### PR TITLE
[Feature] CRF Briefing Screenshots

### PR DESCRIPTION
**Pull request by Geek-x104**
adds briefing images to CRF, if we need to reuse them we come here, saves looking for them elsewhere. New ones added every so often.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
I've been thinking about this. would you perhaps be more interested in creating a discord thread with all of the AAR mission posts including their briefing img. that way we can just copy all of the text and the imagine from the thread rather then just having the image in the mod.

**Comment by tanaaKa** [comment]
@Geek-x104 Read above

**Comment by Geek-x104** [comment]
> I've been thinking about this. would you perhaps be more interested in creating a discord thread with all of the AAR mission posts including their briefing img. that way we can just copy all of the text and the imagine from the thread rather then just having the image in the mod.

@RandAlThor1 agreed, let me know where you want it and I'll do it when I wake up in the morning

**Comment by Geek-x104** [comment]
I'll put this in #development as `cfc briefing screenshots`

**Comment by Geek-x104** [comment]
Done, will close this

**Pull request closed without merging**
