### PR TITLE
Add Mission Files and Resolves Extra Issue

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:

Add the mission Provins & Figari Breakthrough, made by Geek-x to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Attacking
- [x] US

OPFOR - Defending

- [x] USSR

INDFOR - NA

**Objectives/Win Conditions:**

BLUFOR need to reach the Objective Marker within 60 minutes, OPFOR need to stop them.

**Terrain:**

Eden

**Short mission description:**

US Army attempts to move though Provins and Montignac and Soviet forces attempt to stop them.

**Slotting Ratio:**

BLU 3:2 OPF

**Time limit:**

60 minutes

**Design concept/thoughts:**

N/A

**Other Notes:**

GM Notes:
- Minefield is a fluke and doesn't exist, so if people leave game area, will need to put mines down.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
QA Feedback

- Move BLUFOR start, having BLU move in a clear line restricts the amount of gamey abuse that can happen.
image

- When you claim minefields exist, make sure you actually place down the prefabs.
- 2 m113s will be enough, OPFOR will likely already lack AT, and with how comparable vehicles have been performing 3 will likely be too many.

**Comment by Geek-x104** [comment]
doing now, thanks for feedback

**Comment by tanaaKa** [comment]
Reminder as well. Players have consistently asked for infantry focused missions. Reference last weeks AAR:

https://discord.com/channels/237991125523103747/1245866335708119071/1246620078552649729

**Comment by Geek-x104** [comment]
makes sense, will retool now

**Comment by Geek-x104** [comment]
Where i've had to put BLUFOR so they're out of sight from OPFOR they're quite a distance so I have given them trucks, i can put down blockers if wanted so they go on foot but its the best way to get em to the front lines
also will include briefing pic for aar post shortly

**Comment by Geek-x104** [comment]
forgot the minefield by accident, adding now

**Comment by Geek-x104** [comment]
Briefing screenshot:
image

**Comment by RandAlThor1** [comment]
QA Feedback

- Situation should be updated to mention Montignac 
- Given OPFOR not starting in Provins proper, BLUFOR brief saying something informing them that could help BLUFOR plan more towards speed as they can compete to occupy the town.

Otherwise looks good

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
