### PR TITLE
Add adjustable bomb site object

### PR DESCRIPTION
**Pull request by tanaaKa**

### CODE REVIEW

**Review by JessevGool — COMMENTED** [review]
LGTM, can test in a few hours if no one has done so yet

**Comment by Geek-x104** [comment]
Tried changing the object to a replacement (fully set up identically to the original just with a different model) and the bomb is no longer appearing.
The S&D object in the Lobby entity is fine.

**Comment by tanaaKa** [comment]
What object?

**Comment by Geek-x104** [comment]
Originally "GeneratorAirfield_US_01.et", set up a different object as that one doesn't show default in the parent context list.

Regardless, if you try to copy the link to any object from the world editor, it doesn't work, I am now testing by reverting the object to it's original and manually entering the name of the new object.

**Comment by tanaaKa** [comment]
You can't just paste a prefab entity name there. It needs to be the resource path via "Copy Resource Name(s)"
image

It should come out to something like `{3E562E27A2B86F47}Prefabs/Structures/CRF_Bomb.et`

**Comment by Geek-x104** [comment]
Tested it and it worked, the bomb changed however now there is no plant or detonate option, gimme 5-10 to troubleshoot this however overall it looks pretty good to me. (i'm chalking it up to user error on my end if people find/are finding that they are able to set up new entities fine)

**Comment by tanaaKa** [comment]
Yep, changing the entity will involve setting up a new entity with the appropriate bomb plant/defuse action assigned in a location relevant to them.

**Comment by tanaaKa** [comment]
Also someone needs to approve

**Review by Geek-x104 — APPROVED** [review]
look good

**Comment by Pi123263** [comment]
Bröther I request ~~lämp~~ the use of stringtable entries
I'll just throw that in in a later language commit

**Pull request merged**
