### PR TITLE
Add HVT/Exploding Backpack gamemode

### PR DESCRIPTION
**Pull request by Pi123263**
This is a draft/WIP PR to share my current progress on:
Creating a custom explosive satchel with multiple variants, including placeable and backpack variants

A gamemode using that backpack satchel as a tool to destroy enemy bases

WIP stuff:
Backpack satchel:
- [ ] Movement link rigging thingyblobs so it sticks to the body rather than just being roughly attached

satchel gamemode;
- [x] add side-checking so people cant blow up their own base
- [x] general fancyfying

### CODE REVIEW

**Comment by Pi123263** [comment]
Currently WIP features:
Placeable satchel:
the whole arming feature doesnt work yet
general improvements

Backpack satchel:
Movement link rigging thingyblobs so it sticks to the body rather than just being roughly attached
general improvements

satchel gamemode;
move script from triggers to more general game logic if possible, similar to s&d
add side-checking so people cant blow up their own base
add destruction countdown + checks if alive/in vehicle
general fancyfying

**Comment by Pi123263** [comment]
Since we are getting vanilla satchels soon(tm) I'll propably be putting the placable satchels on the backburner, throwable satchles will still be in as normal since thats not possible with the vanilla satchels I think

**Comment by Pi123263** [comment]
@tanaaKa If you have time at some point, it'd be nice to get some eyes and opinions on the trigger code for the hvt gamemode

**Comment by Pi123263** [comment]
Adjusted WIP content targets

**Comment by Pi123263** [comment]
@RandAlThor1 I'd appreciate it if you can do a QA Pass over the new test mission (Pie_BB_Test3 on Eden) <3, feel free to note any bugs you come across during that with the bomb backpack itself as well

As far as im aware this gamemode and the related equipment should now be functional at least to a necessary level, I only have some cosmetic improvements for the backpack and a code rewrite in mind at the moment.

**Comment by RandAlThor1** [comment]
QA Feedback

- snipers? why?
- the 1980s HAT prefab doesn't exist. (of course we just added mods that will likely readd it) you don't need it anyways.
- the way this is described makes it feel like a special. which is FINE, but I don't believe its supposed to be.
- this mission doesn't need so many assets, trim it down.
- some of the scripting text needs a once over.

Overall If you told me this was a gamemode for specials that would be fine, it has the framework of normal missions but the concept of the "bomb backpack" is a tad to much nonsense for me to allow it in CFC missions

**Comment by Pi123263** [comment]
Might just make it a spcl then :(
What would you prefer as an alternative for making it a full on game mode? Vehicle borne explosive or something like that?

**Comment by RandAlThor1** [comment]
the concept of two sides fighting over a bomb to bring it to the others base exploding when there, just doesn't work great for a more serious mission. the backpack bomb in general seems a bit silly, in a good way for a special, but not in a good way for a cfc mission..

physical objectives are good though, having one side tasked with blowing up something is good.

**Comment by Pi123263** [comment]
> the concept of two sides fighting over a bomb to bring it to the others base exploding when there, just doesn't work great for a more serious mission.

So I take that as a 'no'

**Comment by RandAlThor1** [comment]
if your idea was for two people to fight over a vbied to drive it into the opposing base then no. fun special, not cfc tho. we ABOSLUTELY want specials to be played for CFC, they are always fun

**Comment by RandAlThor1** [comment]
@Pi123263 you gonna finish this?

**Comment by Pi123263** [comment]
I should have time again soon since pride season and the relevant events are more of less over

**Comment by RandAlThor1** [comment]
> I should have time again soon since pride season and the relevant events are more of less over

been two weeks, any plans on getting this finished?

**Comment by Pi123263** [comment]
Closing for the time being, dont have the motivation to finish this at the moment, might pick it up again at some point.

**Pull request closed without merging**
