### PR TITLE
Add logi to zeus

### PR DESCRIPTION
**Pull request by tanaaKa**
Adds the two new logi trucks to the zeus interface

### CODE REVIEW

**Comment by RandAlThor1** [comment]
I wasn't able to see these in the GM menu in game,
perhaps I'm missing something, they worked fine in the editor placing the prefabs.

**Comment by RandAlThor1** [comment]
Still not seeing it in the ingame GM menu

**Comment by RandAlThor1** [comment]
Still unable to find it in the entity browser.

**Comment by tanaaKa** [comment]
Closing until we revisit this. No clue why it's not showing.

**Pull request closed without merging**
