### PR TITLE
Smite mountable BTR-70 prefabs to oblivion

### PR DESCRIPTION
**Pull request by GHPCee**
Override mod that should replace the CRF mountable BTRs: https://reforger.armaplatform.com/workshop/617A2E90EA218AC4-GsMountableBTR-70

### CODE REVIEW

**Review by tanaaKa — APPROVED** [review]

**Comment by tanaaKa** [comment]
@Geek-x104 @Pi123263 Did you guys also have missions using this? If so those need removed.

**Comment by Geek-x104** [comment]
Will fix Arleville breakthrough after this weeks mission is finished

**Comment by tanaaKa** [comment]
I will create an issue so we dont forget it.

**Comment by Pi123263** [comment]
> Geek-x104 @Pi123263 Did you guys also have missions using this? If so those need removed.

Only got around to this now since I was on the road for work yesterday, Russian Secrecy uses it as the base for the wonky BTR iirc but that'd need to be removed/fixed befor that can be replayed anyways

**Pull request merged**
