### PR TITLE
Mission/geek special shipment

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:

Add the mission CRF_SPCL90_Shipment made by Geek-x to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [ ] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [ ] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - NA
- [ ] US
- [x] RHS_US_USMC
- [ ] CDF

OPFOR -  NA
- [ ] USSR
- [x] RHS_RF_MSV

INDFOR -  NA
- [ ] FIA

**Objectives/Win Conditions:**
Eliminate the opposing side.

**Terrain:**
Arland

**Short mission description:**
mlg 420 blaze it (US and Russians fight over a familiar location.)

**Slotting Ratio:**
1:1

**Time limit:**
10

**Mission Briefing Screenshot:**
(can upload a proper screenshot if wanted but it only has objectives, notes and welcome and no gamezone markers because it's a compound.)

**Other Notes:**
If anyone manages to escape, just TP them back in. Made it as watertight as possible but it might have holes in it.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
**QA Feedback**

- I see the COD is coming out in briefings now haha
image

- both spawns should probably be accessible by both sides in case someone does "sit in spawn like a giant pussy" so they can still be killed.
- given the numbers I feel like that map should be a bit bigger

**Comment by Geek-x104** [comment]
tbh i hate how i built the spawns, it was to stop spawn rushing, and ye ima make the map a bit bigger, try and keep the same design but just change it a bit

**Comment by Geek-x104** [comment]
rebuilt the spawns and made it bigger

**Comment by Geek-x104** [comment]
also tempted to remake the loading graphic for the loading screen

**Comment by Njpatman** [comment]
> also tempted to remake the loading graphic for the loading screen

do it

**Comment by Geek-x104** [comment]
bet

**Comment by RandAlThor1** [comment]
**QA Feedback** 

- Please put a blocker between the spawns, map overall could probably use more clutter
image

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
