### PR TITLE
Add Mission files

### PR DESCRIPTION
**Pull request by Geek-x104**
This Pull Request will:

Add the mission CRF S&D128 Lamentin made by Geek-x to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [x] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - Attacking
- [x] USSR
- [ ] RHS_RF_MSV

INDFOR - NA
- [ ] FIA

**Objectives/Win Conditions:**
BLUFOR:
Defend their portable generators from OPFOR for 45 minutes.
OPFOR: 
Destroy BLUFORs portable generators within 45 minutes.

**Terrain:**
Eden/Everon

**Short mission description:**
US Forces defend their portable generators from Soviet attack.

**Slotting Ratio:**
OPF 3:2 BLU

**Time limit:**
45 Minutes

**Mission Briefing Screenshot:**
image

**Other Notes:**
Vehicles: 2x BTR70 (Base Game)

### CODE REVIEW

**Comment by Geek-x104** [comment]
will drop briefing ss shortly

**Comment by RandAlThor1** [comment]
**QA Feedback**

- 1LAT should be MAT, and their squad name should be changed to Medium Anti-Tank instead of Anti-Tank Team
- make sure the slotting ratio is closer to the missions 3:2 ratio, right now its 2:1
- objectives for brief should be one section not three
image
- opfor coy needs to be a coy not a plt lead
image
- if its gonna be outside like this, it should probably be the old prefab
image
- make sure both sides have at least one medical vehicle for MOs
- you have 132 slots, we can't have over 128, change the total slot count to no higher then 128
- (4 squads per russian PLT is alot. 2 lets them mount on a BTR each, 3 is the normal max)
- BTRs don't need a commander.

**Comment by Geek-x104** [comment]
> objectives for brief should be one section not three

I'm gonna remove the Secondary Objective, but the 2 objectives are both worth 50 points for each of the bombs.

**Comment by Geek-x104** [comment]
> opfor coy needs to be a coy not a plt lead

aight, will also update the group because it still had Platoon Leader

Update: Thought it was still Platoon Large not Company, my bad

**Comment by RandAlThor1** [comment]
> > opfor coy needs to be a coy not a plt lead
> > aight, will also update the group because it still had Platoon Leader

You just placed the wrong prefab, the group prefab for COY has coy in it. the group prefabs in the CRF don't need to be updated. just change the PLT character in your first group to COY and your good

image

**Comment by Geek-x104** [comment]
> > > opfor coy needs to be a coy not a plt lead
> > > aight, will also update the group because it still had Platoon Leader
> 
> You just placed the wrong prefab, the group prefab for COY has coy in it. the group prefabs in the CRF don't need to be updated. just change the PLT character in your first group to COY and your good

ye just noticed XD

**Comment by Geek-x104** [comment]
> > objectives for brief should be one section not three
> 
> I'm gonna remove the Secondary Objective, but the 2 objectives are both worth 50 points for each of the bombs.

@RandAlThor1 let me know if this is fine, if not i can change it now

**Comment by Geek-x104** [comment]
> if its gonna be outside like this, it should probably be the old prefab

also, moving this inside

**Comment by RandAlThor1** [comment]
**QA Feedback**

- Asset briefing is supposed to be same for both sides, so neither side is surprised by an asset.
- related to above.
when you have a COY element its important to distinct if an asset is COY or PLT level. each BTR and one MMG team should be at the bottom of their own PLT with the medic team at the complete bottom. 
- place those MMG teams and 1 BTR each under their respective platoon.
- this site is too hidden, the goal is for players to defend an area. not for it to be obscure.
image

**Comment by Geek-x104** [comment]
> this site is too hidden, the goal is for players to defend an area. not for it to be obscure.

Moved this to roof.

**Comment by Geek-x104** [comment]
@RandAlThor1 made changes, if the bomb is still inside lmk and I'll push a fix

**Comment by RandAlThor1** [comment]
**QA Feedback**

- These three tabs say literally the same thing. (just remove situation and objective if your just gonna put nothing of note in them)
image
- asset tab should be visible to everyone even non slotted members so admins can see what is in play asset wise and if anything needs to be changed.

nothing else I can see

**Comment by Geek-x104** [comment]
This is how my the AAR looks now

image

**Comment by Geek-x104** [comment]
added briefing screenshot to original message

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
