### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Arkangel-Vigilamus**
Renamed game modes
Added Neutral Escort mission description
Kill trigger on Rally Meaux was broken on the revert, so I deleted it. 
Safe start now working on Rally Meaux

### CODE REVIEW

**Comment by Arkangel-Vigilamus** [comment]
I fucked up the neutral escort description, I'll make another commit to fix.

**Review by Njpatman — CHANGES_REQUESTED** [review]
Remove resoursedatabase.rdb change or open up a new PR without the resource database change.

Also, talk to JLaw about getting his trigger scripts and just replicate his end trigger in your rally.

**Comment by tanaaKa** [comment]
You need that trigger imo. You can just open up rally coast and copy it over.

**Comment by Njpatman** [comment]
push a commit that replaces the resoursedatabase.rdb file with the one in release and I'll call this good

**Pull request merged**
