### PR TITLE
Sal muddy munster

### PR DESCRIPTION
**Pull request by Salamiboio**
This Pull Request will:

Add the mission Muddy Munster made by salami to the repository.

**Mission Creation Checklist:**
- [X] Mission File
- [X] Ingame Play Area Markers
- [X] Ingame Briefings to all players
- [X] Side-based briefings
- [X] Objective Entities
- [X] Mission .conf file

**Faction(s):**
BLUFOR - Attacking/Defending/NA
- [X] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - Attacking/Defending/NA
- [ ] USSR
- [ ] RHS_RF_MSV

INDFOR - Attacking/Defending/NA
- [X] FIA

**Objectives/Win Conditions:**

S&D 
OBJ A - Water Treatment Plant
OBJ B - Mussalo Factory

**Terrain:**

Mussalo

**Short mission description:**

US forces attack FIA insurgents setting up bombs in the Mussalo Water Treatment Plant and Factory.

**Slotting Ratio:**

BLU 3:2 FIA

**Time limit:**

45 Min

**Mission Briefing Screenshot:**
image

**Design concept/thoughts:**

An superior US platoon fights an undermanned, disjointed insurgent force on a time limit. RPG teams to compensate for HMMWV support.

**Other Notes:**

Ensure blufor is only taking 1x Armed HMMWV and 1x Unarmed HMMWV per squad. If theres 3x Squads there should be 3x Armed and 3x Unarmed HMMWVs as well as the respective platoon and HQ trucks.

### CODE REVIEW

**Comment by RandAlThor1** [comment]
**QA Feedback**

- FIA has no lead element
image

- we don't need OBJ A, and OBJ B brief. its explained in the IND/BLUFOR brief and gametype 
image

- Attacker Mortars aren't usually great because unlike defender ones there is no way to counter them, with all of their vehicles they will have plenty of assets.

- When defenders have mortars. a) make atk spawn less obvious b) don't start them in range with a narrow range to attack. (move blufor spawn back so its out of range of the indfor mortars and give them a bigger width to attack from)

- your mission name and your actual player count do not line up
image

- Mortars don't actually require loaders, I just have them in the group prefab for when they eventually will.
image

- your lacking Objective entities so there is on objectives on the end screen.
image

- you actually do have some, but their faction key is not set. you need 1 for boths sides per objective. set their respective score to 50 for each.
image

- indfor mortars have ALOT of ammo, give them less. make them think twice about shelling the shit out of something

**Comment by Salamiboio** [comment]
No Lead Element is intentional cause they are cells, we've always done FIA and CDF like this.

Mortars will be deleted from ATK, spawn will be moved back.

The Loaders on INDFOR are gonna act like runners for ammo, that's why I put it so far away in the factory.

Will fix Objectives.

Will halve mortar ammo.

**Comment by RandAlThor1** [comment]
> No Lead Element is intentional cause they are cells, we've always done FIA and CDF like this.

no we very much haven't. every mission with FIA and CDF have operated with a lead element, you need one for any sort of player cohesion.

> The Loaders on INDFOR are gonna act like runners for ammo, that's why I put it so far away in the factory.

then move the ammo closer and delete the loaders, thats not fun gameplay

**Comment by Salamiboio** [comment]
Added FIA Lead element

Fixed Objectives.

Deleted BLUFOR Mortar and replaced with a scout section.

Reduced INDFOR Mortar ammo by half.

Fixed Mission Config

Deleted Loaders

**Comment by RandAlThor1** [comment]
**QA Feedback**

- The Faction manager is for callsigns and the groups are for squad names 1-1 vs 1st squad. both need to be set for things to show up correctly via the map and what not. right now you just have faction manager callsigns set.
image

- blufor spawn flag needs to be moved to new spawn location
image

- the mortars will need a trigger to spawn them in, see Sweep of Stary Yar on Chernarus for an example of the script
image

**Comment by Salamiboio** [comment]
Added mortar spawn script
Adjusted Mortar spawn
Added Marker for mortars
Fixed BLUFOR spawn marker
Fixed Lobby callsigns

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
