### PR TITLE
Geek missions

### PR DESCRIPTION
**Pull request by Geek-x104**

### CODE REVIEW

**Review by Njpatman — CHANGES_REQUESTED** [review]
Hi Geek, please update this PR to the latest version of the CRF or close it out.

**Comment by Geek-x104** [comment]
Understood, will do asap

**Comment by Njpatman** [comment]
> Understood, will do asap

Let me know if you want to update this to the S&D Gamemode

**Comment by Njpatman** [comment]
Closing to help update geek to release

**Pull request closed without merging**
