### PR TITLE
[Mission Update] TVT96 Into The Breach V2

### PR DESCRIPTION
**Pull request by HitTheMan**
- Adjusted Name to reflect changes
- Removed 2x BTRs from OPFOR, seperated the 1x BTR from 1st Squad to be Independent
- Replaced 2x HMMWVs with 50.cal variants (1x per squad)
- Added 40mm smoke to HMMWVs
- Fixed M72A3 in HMMWVs
- Added extra units to OPFOR's Squad to make up loss of BTR (For ratio)
- Adjusted OPFOR squad layout to removed 1x GL and replace with AR/Rifle
- Adjusted ASSET Briefing to fix confusion and updated assets 

NOTE wanting to replace HMMWVs with M113s in the near future when they're introduced

### CODE REVIEW

**Comment by RandAlThor1** [comment]
QA Feedback

- remove the "(BTR)" from the USSR squad names as they no longer have them
- don't add the V2

once that's done I'll approve.

**Comment by HitTheMan** [comment]
Changed this mission based on feedback + personal changes

- Readded BTRs to 1st & 2nd Squad of OPFOR, 3rd Squad has 2x Rifleman still and BTR removed from their name
- Added 1x Mortar + 1x Gunner to BLUFOR
- Removed all Medical Officers from Platoon and moved them into COY (3x Medics, 1x changed into Mortar)
- Fixed Weapon Squads to now include M67 Teams
- Removed V2 from name, will be documented here

Edit:
Forgot to mention:
- Renamed ArmourCrew in OPFOR into VCommander, and added VGunner & VDriver, along with their rolename changes.

**Comment by HitTheMan** [comment]
- Removed Mortar from map
- Added a note "- Mortar AMMO should be at(4x Mags or 24x Shells, 6x per mag" in mission notes & Assets

**Comment by RandAlThor1** [comment]
QA Feedback

- OPFOR PLT needs to be rebuilt, the entity is missing its components
image

- make sure you grab the script that was used to delay the spawn of the mortars, you can find this on your sweep of stary yar mission.
- mortar battery needs to be updated to be a two man team with lead and gunner.
- I would probably update the slots to use the new prefabs, but isn't 100% needed.

**Comment by tanaaKa** [comment]
@HitTheMan Requesting update on this

**Review by RandAlThor1 — APPROVED** [review]

**Pull request merged**
