### PR TITLE
[Mission] TVT90 Bridge Breakthrough

### PR DESCRIPTION
**Pull request by HitTheMan**
First mission made by HTM for Coalition

Mission Pull Request Template

This Pull Request will:

Add the mission <mission name!> made by <author name!> to the repository.

**Mission Creation Checklist:**
- [x] Mission File
- [x] Ingame Play Area Markers
- [x] Ingame Briefings to all players
- [x] Side-based briefings
- [x] Objective Entities
- [x] Mission .conf file

**Faction(s):**
BLUFOR - Defending
- [x] US
- [ ] RHS_US_USMC
- [ ] CDF

OPFOR - Defending
- [x] USSR
- [ ] RHS_RF_MSV

INDFOR - NA
- [ ] FIA

**Objectives/Win Conditions:**

OPFOR:
Capture & secure 3x Bridges following a highway/railway
Render BLUFOR combat ineffective

BLUFOR:
Defend 3x bridges along the highway/railway
Render OPFOR combat Ineffective

**Terrain:**

Mussalo

**Short mission description:**

A US Platoon (-) is to defend the peninsula to hold out until a Engineer unit can arrive from Company to blow up the bridges before withdrawing across the river
A USSR Company (-) is to secure & hold those bridges before they manage to blow them up, to allow their battalion to proceed with their attack vector further in

**Slotting Ratio:**

OPFOR <2:1> BLUFOR

**Time limit:**

<60min>

**Mission Briefing Screenshot:**

order

**Design concept/thoughts:**

I wanted to expend upon the mission from previous experienced on Coalition as would my friends, so with this it'd hopefully allow a more broader expanse on how the Commanders approach this scenario and make plans to succeed it in their own ways, with a large enough AO to allow for different approaches & replayability, and enough scaling to allow playability by a range of populations.

With there only being BTR70s & HMMWV 50.cal that can really be used (Can't quite trust the use of T-14, K-17, 2S1 as its a artillery piece, etc) and the general lack of variety of armed vehicles for BLUFOR/NATO, made the most sense to make both motorized but would prefer to have made them M113s, BMPs, etc. Also a lack of TOW capability or AT for BLUFOR/NATO that isnt M72A3 also limits the use of armour without further proper testing of damage models for the armoured vehicles existing and how "reliably" a player can kill a vehicle should it need to for Force Factoring when it comes to ratios.

But TLDR a Attack/Defend Breakthrough or "Sweep & Secure" kind of mission where BLUFOR have to establish minefields, at junctions they deem fit to help them along with delaying points, ambush points, etc to hurt OPFOR whilst OPFOR have to find a way to penetrate the defences or manage to bypass them to get towards the bridges & secure them.

**Other Notes:**

(Notes taken from Briefing In-Game)
Mission Notes:
- 70min Timelimit / OPFOR 2:1 BLUFOR
- OPFOR cannot leave their safe zone until the game starts.
- BLUFOR cannot leave their AO Limit and must stay inside it, with the encouragement to stay close to the Bridges.
- No excess use of Armed Vehicles than what is assigned to them (Check Global Assets)

Notes for Admin/Game Master:
- Spawn S1203 Ambulance for OPFOR
- Spawn HMMWV Ambulance for BLUFOR
- Each Trigger on the bridge is 100m Wide and will trigger once OPFOR has 0.8 Ratio over BLUFOR, it checks every 20sec

### CODE REVIEW

**Comment by FluffSquirrel** [comment]
i think "terrain" means what map is it on

**Comment by RandAlThor1** [comment]
QA Feedback
------------
Prefabs
Not gonna fail the QA check for either of these, just comments. I understand you wanted the clean 30/60 slot split and I can appreciate that.
- OPFOR company does not need 3 leads, this has no real application in arma. (also, if COY is meant to use a BTR, replace the riflemen with crew)
- BLUFOR Platoon sergeant plays little to no role in arma, this is why they either don't exist or are replaced with JTAC/FO when needed.
-----------
mission notes comments
- Mission Notes cuts off split it in two.
- 90 minutes is ALOT to finish this mission, the normal 60 will probably be more then enough.
- people will hug the AO, if its in play, it will be used.
- vehicles are assigned to crew
-------
Technical Notes
- breakthrough mission types are a specific type of mission that we play, that requires one side to effectively "reach" a certain destination. you can find a rough description here: https://coalitiongroup.net/wiki/index.php/Breakthrough
- I don't think it would be crazy to add a trigger as described in the wiki for this mission perhaps on the other side of bridge 3.
- we need a global briefing usually labeled "situation" so it can be included along with a photo of the AO similar to the image below
image
- The "terrain" on the github template is meant to be the map
- in the github template make sure to delete the excess faction/roles so we can tell at a glance who is who see below
BLUFOR - Attacking/Defending/NA -> BLUFOR - Defending
OPFOR - Attacking/Defending/NA -> OPFOR- Attacking

- some vehicles cause missions to not load, this is a reforger issue. reference this message: https://discord.com/channels/237991125523103747/468879945293234177/1258809499750240407 Remove the needed vehicles and they will be added back by admins on mission start, just make sure the notes in here and the Asset briefing are accurate to what is needed.

- If these changes can be made today, we will hopefully be able to have a QA session tomorrow to ensure your scripts work
-----

**Comment by HitTheMan** [comment]
Appreciate the review so here's my point of view:

Prefabs:
- Guess it's just my old ways as we used to have company leads with platoon elements under them, the real use is less gameplay and more milsimy I.E more communication & lead element but I'll remove COY HQ and find a way to replace them with another unit to maintain the 60/30 split, too many 3:2 ratios in my opinion so giving 2:1 a go 😄 

- Reason for PLT SGT is more for a 2 reason:
1. A defined 2iC that'll take over if PLT CO takes a hit
2. delegate the other squads should he need to if the PLT CO is preoccupied, from previous experience on ArmA be it ArmA 2, ArmA 2 OA & ArmA 3 they were immensely useful but that's our experience

Mission notes:
- Aaah guess it's tied to screen resolution that makes things difficult especially without a scrollbar, I'll adjust it & simplify it further
Potentially, depends on how BLUFOR act as they can slow down OPFOR if they're real clear on that intention, so giving OPFOR some more wiggle room, not as long as other missions at 120min but not as normal with 60min, I'll set it at 70min so they have time to properly clear out the areas they have to to proceed without feeling a pressure of "we need to rush go go" leading to less fun gameplay in my personal opinion if that is alright 😄 
- And yeah regarding AO hugging not always will happen but just me writing there to encourage the OPFOR CO to not do it but it's entirely up to them if they wish to do so, but I can remove it to simplify the mission note list
- Aah yeah seen think I must have missed since the other units have ArmourCrew for their BTR, I'll fix that

Technical notes:
- Yeah the only issue I have is they can bumrush without really "pushing", why I added 2x more objectives for them to secure slowing the pace down whilst giving blufor more time to relocate, OR if opfor desire they can attack from the west in the woods, just there to give BLUFOR more chance to relocate to handle the situation, I'll rename the gamemode to something else
- Yeah wouldnt be hard now just.. I really do not want to encourage OPFOR to simply "Rush" the objective mounted, I want to encourage slowing down the pace of movement & firefights to fight over 3 vital bridges 😄 
- I figured out my confusion and I'll fix it 
- Gotcha I'll update that
- I did not see that anywhere I'll look into it as I am unsur where it is

- Regarding vehicles, thats good to know just.. makes it hard as I want them to have specific loadout. I'll remove them but I'll likely add a box with the required equipment for the players to add I.E more M72A3s for Blufor, 30x AT Mines (specifically 30x AT mines), more ammo for mainline weaponry and diversity

I'll get these changes worked on tonight (today for you in the US)

**Comment by RandAlThor1** [comment]
Let me specify on opfor coy.
Having coy is absolutely good. It's the three leader positions in the coy itself that is a bit much. Not the end of the world, but those slots will likely not get slotted anyways

**Comment by HitTheMan** [comment]
> Let me specify on opfor coy. Having coy is absolutely good. It's the three leader positions in the coy itself that is a bit much. Not the end of the world, but those slots will likely not get slotted anyways

Yeah after re-reading I understood I misread and thought you meant having 3x Lead Units was a bad thing but I understand now 😄

**Comment by HitTheMan** [comment]
Changelog:

- Replaced OPFOR COY 1stSergeant with a 2nd Medical Officer
- Replaced OPFOR COY Rifleman with ArmourCrew
- Replaced S1203 Ambulance with S1203 that has shit ton of medical for the medics
- Changed Mission Notes trimmed (sad it doesnt have a scrollwheel for large texts)
- Changed Timelimit from 90min to 70min
- Changed gamemode name from "Breakthrough" to "Sweep & Secure"
- Added Screenshot acquired for Git in regards to situation + AO
- Added Terrain Name
- Changed Vehicles (mentioned above)

**Comment by tanaaKa** [comment]
For future reference:

Briefings:
Global (all factions):
- Welcome
- Situation
- Assets

image


Side-based:
- Objective Entities
- Optional: Side-based briefings

Make sure you set the z order on these appropriately so they're not mixed up. The objective entity titles should be along the lines of OBJ: Objective Name

**Comment by RandAlThor1** [comment]
The ambulance vehicle serves a mechanical purpose beyond providing supplies. It allows for MOs to bring back serious casualties while within their radius

**Comment by HitTheMan** [comment]
> For future reference:
> 
> Briefings:
> 
> * Welcome
> * Situation
> * Assets
> * Objective Entities
> * Optional: Side-based briefings
> 
> Make sure you set the z order on these appropriately so they're not mixed up. The objective entity titles should be along the lines of OBJ: Objective Name

Solid atm the briefings have a Z order along with written order in them, here's the BLUFOR perspective of their briefing
order

But I'll adjust the briefings to contain as per mentioned above with welcome, situation, etc 😄 



> The ambulance vehicle serves a mechanical purpose beyond providing supplies. It allows for MOs to bring back serious casualties while within their radius

Gotcha sorry still not used to thinking a GM/Admin available throughout the mission, I'll remove the S1203 and instead add a note to spawn in a S1203 Ambulance for OPFOR that the admin can do 😄

**Comment by tanaaKa** [comment]
> > For future reference:
> > Briefings:
> > 
> > * Welcome
> > * Situation
> > * Assets
> > * Objective Entities
> > * Optional: Side-based briefings
> > 
> > Make sure you set the z order on these appropriately so they're not mixed up. The objective entity titles should be along the lines of OBJ: Objective Name
> 
> Solid atm the briefings have a Z order along with written order in them, here's the BLUFOR perspective of their briefing order
> 
> But I'll adjust the briefings to contain as per mentioned above with welcome, situation, etc 😄
> 
> > The ambulance vehicle serves a mechanical purpose beyond providing supplies. It allows for MOs to bring back serious casualties while within their radius
> 
> Gotcha sorry still not used to thinking a GM/Admin available throughout the mission, I'll remove the S1203 and instead add a note to spawn in a S1203 Ambulance for OPFOR that the admin can do 😄

Oh I'm aware and as a former infantry man, I'm telling you that briefing sucks. No one wants to read an opord in the military despite their argued effectiveness. You definitely won't get a casual player to do it.

Collapse all of the OPORD info into a singular briefing labeled BLU/OPF briefing and put all of that info in there, separated by headers.

Also, full transparency, this isn't your other community. While ideas are 100% open and welcomed, there's also a standard we have. We can obvious talk about changing that standard, but the QA done here and the pull request is to get your mission to our standard.

**Comment by HitTheMan** [comment]
Reply to TanaKa:

Yeah no I appreciate that hence me changing it, I only showed the screenshot to show that they are Z ordered so there won't be any mismatched but as I said I'll change the briefing to be set to a standard, I did not see a standard briefing format on the wiki nor pinned in the discord channel so I rolled with habit to write one

I'll be combining the briefings & writing it differently to the standard you've now shown me, would be nice if there was a section on the Wiki saying what the expected layout would be as you wrote here 😄 

And I very much appreciate you pointing that out again I'm only making and writing by how I personally did it, which is very much subject to be needed to change, this is a whole different community, with a whole different QA standard & expectation and a whole different playerbase, I did not mean to encroach on that or push into it I wrote the briefing with the thought it'd add some flavour to that mission itself from my personal experience, again I will be overhauling it completely and appreciate you pointing it out 😄

**Comment by HitTheMan** [comment]
Changelog:

- Removed S1203 & added note to mission notes regarding adding a S1203 Ambulance for OPFOR
- Removed the 3rd unarmed HMMWV from BLUFOR & added note to mission notes regarding adding a HMMWV Ambulance for BLUFOR
- Changed Briefing Format to consist of this:
-- Welcome (Using #Coal_Missions_Lobby_Welcome_Title & #Coal_Missions_Lobby_Welcome_Text found in Sabotage mission)
-- Situation
-- Assets
-- Objective (1x per side as seen on other missions)
-- Vehicle Inventory (1x per side, To show what each vehicle has in its inventory that is vital like M72A3 rockets, AT Mines, Ammo, etc)
-- Mission Notes
- Replaced BLUFOR Platoon Sergeant wih 2nd Medical Officer (2x officers for HMMWV Ambulance, similar to OPFOR)
- Replaced OPFOR COY Deputy Officer with Rifleman
- Replaced OPFOR Platoon Deputy with Rifleman
- Changed mission timelimit from 70min to 60min
- Changed weather from Thunderstorm to Rainy
-- Changed dependency to remove Bacon Weather

Edit:
Here's the new Briefing POV from BLUFOR:
order

Edit 2:
Fixed briefing that didn't save properly (Assets)

**Comment by HitTheMan** [comment]
I forgot to hit "Push Origin" on GitHub Desktop yesterday so the changed I spoke about never reached the published branched

It should be be fully updated with the latest changelogs + added objective entities, I've seen some missions not have them but I've made sure to add 6x Objective Entities, 2x per objective, 3x per side for Attack/Defend + score values

**Comment by RandAlThor1** [comment]
QA Feedback

I've been thinking about this, and I don't really think the bridge blowing thing is really good gameplay for what CFC TVTs really are. for our TVTs we are probably going to want anything like that to be caused through direct player action, rather then some non existent "coy" that comes and blows it up.

The rest of the mission is setup really well, and 95% of the gameplay is just a regular sweep mission similar to the second mission we played last week. keep the mines and remove the bridge detonation thing, and we should have a fun mission on our hands.

I would 100% say that once we get our CO-OP missions flowing on sundays, that scripting like this could absolutely make for some good times.

**Comment by HitTheMan** [comment]
> QA Feedback
> 
> I've been thinking about this, and I don't really think the bridge blowing thing is really good gameplay for what CFC TVTs really are. for our TVTs we are probably going to want anything like that to be caused through direct player action, rather then some non existent "coy" that comes and blows it up.
> 
> The rest of the mission is setup really well, and 95% of the gameplay is just a regular sweep mission similar to the second mission we played last week. keep the mines and remove the bridge detonation thing, and we should have a fun mission on our hands.
> 
> I would 100% say that once we get our CO-OP missions flowing on sundays, that scripting like this could absolutely make for some good times.

So quick disclaimer there is no bridge detonation it's pure text flavour for Why X does Y, had no plans to really setup a script or situation about the bridges being blown but purely give reason for why BLUFOR is there to protect the area and why OPFOR is sending a overwhelming force (not quite but you get what I mean)

I can remove that text however if we don't want to "mislead" the players with that flavour text and purely say BLUFOR is there to deny OPFOR their goal of securing the bridges, instead of being there until they can "blow" it up? 😄

**Comment by RandAlThor1** [comment]
My misunderstanding came from this part of the mission notes
image

plus with the old mission notes, I was under the impression there was a script about the bridges being destroyed.

**Review by RandAlThor1 — APPROVED** [review]

**Comment by HitTheMan** [comment]
> My misunderstanding came from this part of the mission notes image
> 
> plus with the old mission notes, I was under the impression there was a script about the bridges being destroyed.

Oh no that is just telling the current acting admin/gm that the Radius of the script is 100m, and for OPFOR to have "secured" the bridge is they need to be in a 0.8:0.2 ratio inside that radius, and that it checks it every 20seconds
Incase they were on the bridge & nothing is happening 😄 

I'll most likely have to tweak it after a proper game has been done but I'm hoping with the potential replay-ability it can be played a few times IF it's a enjoyable mission, if not then ohwell it was a good test-bed for me to learn Workbench & Enforce Script a little 😄

**Pull request merged**
