### PR TITLE
Fixes #19

### LINKED ISSUE #19: Modern Russian Gear Script no Flashlight and Radio
There is an issue with Russian modern loadouts, They are not getting the flashlight and radio even though it in their inv component.
image
image

### PR DESCRIPTION
**Pull request by MrPvTDagger**
As @tanaaKa mentioned in #19 there are no slots on the vest cause they are on the jacket... (Looking at you RHS Team)

- Moved the range finder to the backpack as no room in the jacket for it hence it was being removed.
- Switched the RU radio to 148 as it was 187 which is a backpack radio.

### CODE REVIEW

**Comment by tanaaKa** [comment]
We dont want to use the RHS 148. It's buggy. Give them the default reforger soviet radio and we can close this.

**Comment by MrPvTDagger** [comment]
It should already be the default reforger soviet radio they are both called 148.

**Comment by MrPvTDagger** [comment]
The RHS one is 187

**Comment by tanaaKa** [comment]
Well that's dumb

**Pull request merged**
